/* THIS FILE IS AUTOGENERATED, DO NOT EDIT */

module.exports.textUtilities = {
  '.text-mono-xs': {
    'font-family': '"GT America Mono", monospace',
    'font-weight': 400,
    'font-size': '0.625rem',
    'letter-spacing': '0.04rem',
    'text-transform': 'uppercase',
  },
  '.text-mono-sm': {
    'font-family': '"GT America Mono", monospace',
    'font-weight': 400,
    'font-size': '0.6875rem',
    'letter-spacing': '0.04rem',
    'text-transform': 'uppercase',
  },
  '.text-mono-md': {
    'font-family': '"GT America Mono", monospace',
    'font-weight': 400,
    'font-size': '0.75rem',
    'letter-spacing': '0.04rem',
    'text-transform': 'uppercase',
  },
  '.text-mono-lg': {
    'font-family': '"GT America Mono", monospace',
    'font-weight': 400,
    'font-size': '0.875rem',
    'letter-spacing': '0.04rem',
    'text-transform': 'uppercase',
  },
  '.text-sans-xl': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 300,
    'line-height': '1.5375rem',
    'font-size': '1.1875rem',
    'letter-spacing': '0.02rem',
  },
  '.text-sans-2xl': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 300,
    'line-height': '2.025rem',
    'font-size': '1.5625rem',
    'letter-spacing': '0rem',
  },
  '.text-sans-3xl': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 300,
    'line-height': '3.24375rem',
    'font-size': '2.5rem',
    'letter-spacing': '0.015rem',
  },
  '.text-sans-sm': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 400,
    'line-height': '1.05625rem',
    'font-size': '0.8125rem',
    'letter-spacing': '0.05rem',
  },
  '.text-sans-md': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 400,
    'line-height': '1.125rem',
    'font-size': '0.875rem',
    'letter-spacing': '0.04rem',
  },
  '.text-sans-lg': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 400,
    'line-height': '1.3rem',
    'font-size': '1rem',
    'letter-spacing': '0.03rem',
  },
  '.text-sans-semi-sm': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 500,
    'line-height': '1.05625rem',
    'font-size': '0.8125rem',
    'letter-spacing': '0.05rem',
  },
  '.text-sans-semi-md': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 500,
    'line-height': '1.125rem',
    'font-size': '0.875rem',
    'letter-spacing': '0.04rem',
  },
  '.text-sans-semi-lg': {
    'font-family':
      'SuisseIntl, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
    'font-weight': 500,
    'line-height': '1.3rem',
    'font-size': '1rem',
    'letter-spacing': '0.03rem',
  },
}

module.exports.colorUtilities = {
  '.text-default': {
    color: 'var(--content-default)',
  },
  '.text-secondary': {
    color: 'var(--content-secondary)',
  },
  '.text-tertiary': {
    color: 'var(--content-tertiary)',
  },
  '.text-quaternary': {
    color: 'var(--content-quaternary)',
  },
  '.text-accent': {
    color: 'var(--content-accent)',
  },
  '.text-accent-secondary': {
    color: 'var(--content-accent-secondary)',
  },
  '.text-accent-tertiary': {
    color: 'var(--content-accent-tertiary)',
  },
  '.text-accent-disabled': {
    color: 'var(--content-accent-disabled)',
  },
  '.text-destructive': {
    color: 'var(--content-destructive)',
  },
  '.text-destructive-secondary': {
    color: 'var(--content-destructive-secondary)',
  },
  '.text-destructive-tertiary': {
    color: 'var(--content-destructive-tertiary)',
  },
  '.text-destructive-disabled': {
    color: 'var(--content-destructive-disabled)',
  },
  '.text-success': {
    color: 'var(--content-success)',
  },
  '.text-success-secondary': {
    color: 'var(--content-success-secondary)',
  },
  '.text-error': {
    color: 'var(--content-error)',
  },
  '.text-error-secondary': {
    color: 'var(--content-error-secondary)',
  },
  '.text-notice': {
    color: 'var(--content-notice)',
  },
  '.text-notice-secondary': {
    color: 'var(--content-notice-secondary)',
  },
  '.text-notice-tertiary': {
    color: 'var(--content-notice-tertiary)',
  },
  '.text-notice-disabled': {
    color: 'var(--content-notice-disabled)',
  },
  '.text-inverse': {
    color: 'var(--content-inverse)',
  },
  '.text-inverse-secondary': {
    color: 'var(--content-inverse-secondary)',
  },
  '.bg-default': {
    'background-color': 'var(--surface-default)',
  },
  '.bg-secondary': {
    'background-color': 'var(--surface-secondary)',
  },
  '.bg-raise': {
    'background-color': 'var(--surface-raise)',
  },
  '.bg-disabled': {
    'background-color': 'var(--surface-disabled)',
  },
  '.bg-raise-hover': {
    'background-color': 'var(--surface-raise-hover)',
  },
  '/* Command menu backdrop */ \n.bg-scrim': {
    'background-color': 'var(--surface-scrim)',
  },
  '.bg-secondary-hover': {
    'background-color': 'var(--surface-secondary-hover)',
  },
  '.bg-accent': {
    'background-color': 'var(--surface-accent)',
  },
  '.bg-accent-secondary': {
    'background-color': 'var(--surface-accent-secondary)',
  },
  '.bg-accent-raise': {
    'background-color': 'var(--surface-accent-raise)',
  },
  '.bg-accent-hover': {
    'background-color': 'var(--surface-accent-hover)',
  },
  '.bg-accent-secondary-hover': {
    'background-color': 'var(--surface-accent-secondary-hover)',
  },
  '.bg-destructive': {
    'background-color': 'var(--surface-destructive)',
  },
  '.bg-destructive-secondary': {
    'background-color': 'var(--surface-destructive-secondary)',
  },
  '.bg-destructive-raise': {
    'background-color': 'var(--surface-destructive-raise)',
  },
  '.bg-destructive-hover': {
    'background-color': 'var(--surface-destructive-hover)',
  },
  '.bg-destructive-secondary-hover': {
    'background-color': 'var(--surface-destructive-secondary-hover)',
  },
  '.bg-success': {
    'background-color': 'var(--surface-success)',
  },
  '.bg-success-secondary': {
    'background-color': 'var(--surface-success-secondary)',
  },
  '.bg-error': {
    'background-color': 'var(--surface-error)',
  },
  '.bg-error-secondary': {
    'background-color': 'var(--surface-error-secondary)',
  },
  '.bg-notice': {
    'background-color': 'var(--surface-notice)',
  },
  '.bg-notice-secondary': {
    'background-color': 'var(--surface-notice-secondary)',
  },
  '.bg-notice-raise': {
    'background-color': 'var(--surface-notice-raise)',
  },
  '.bg-notice-hover': {
    'background-color': 'var(--surface-notice-hover)',
  },
  '.bg-notice-secondary-hover': {
    'background-color': 'var(--surface-notice-secondary-hover)',
  },
  '.bg-inverse': {
    'background-color': 'var(--surface-inverse)',
  },
  '.bg-inverse-secondary': {
    'background-color': 'var(--surface-inverse-secondary)',
  },
  '.bg-inverse-tertiary': {
    'background-color': 'var(--surface-inverse-tertiary)',
  },
  '.border-default': {
    'border-color': 'var(--stroke-default)',
  },
  '.border-secondary': {
    'border-color': 'var(--stroke-secondary)',
  },
  '.border-tertiary': {
    'border-color': 'var(--stroke-tertiary)',
  },
  '.border-raise': {
    'border-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.border-surface': {
    'border-color': 'var(--stroke-surface)',
  },
  '.border-accent': {
    'border-color': 'var(--stroke-accent)',
  },
  '.border-accent-secondary': {
    'border-color': 'var(--stroke-accent-secondary)',
  },
  '.border-accent-tertiary': {
    'border-color': 'var(--stroke-accent-tertiary)',
  },
  '.border-destructive': {
    'border-color': 'var(--stroke-destructive)',
  },
  '.border-destructive-secondary': {
    'border-color': 'var(--stroke-destructive-secondary)',
  },
  '.border-destructive-tertiary': {
    'border-color': 'var(--stroke-destructive-tertiary)',
  },
  '.border-success': {
    'border-color': 'var(--stroke-success)',
  },
  '.border-success-secondary': {
    'border-color': 'var(--stroke-success-secondary)',
  },
  '.border-success-tertiary': {
    'border-color': 'var(--stroke-success-tertiary)',
  },
  '.border-error': {
    'border-color': 'var(--stroke-error)',
  },
  '.border-error-secondary': {
    'border-color': 'var(--stroke-error-secondary)',
  },
  '.border-error-tertiary': {
    'border-color': 'var(--stroke-error-tertiary)',
  },
  '.border-notice': {
    'border-color': 'var(--stroke-notice)',
  },
  '.border-notice-secondary': {
    'border-color': 'var(--stroke-notice-secondary)',
  },
  '.border-notice-tertiary': {
    'border-color': 'var(--stroke-notice-tertiary)',
  },
  '.border-l-default': {
    'border-left-color': 'var(--stroke-default)',
  },
  '.border-l-secondary': {
    'border-left-color': 'var(--stroke-secondary)',
  },
  '.border-l-tertiary': {
    'border-left-color': 'var(--stroke-tertiary)',
  },
  '.border-l-raise': {
    'border-left-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.border-l-surface': {
    'border-left-color': 'var(--stroke-surface)',
  },
  '.border-l-accent': {
    'border-left-color': 'var(--stroke-accent)',
  },
  '.border-l-accent-secondary': {
    'border-left-color': 'var(--stroke-accent-secondary)',
  },
  '.border-l-accent-tertiary': {
    'border-left-color': 'var(--stroke-accent-tertiary)',
  },
  '.border-l-destructive': {
    'border-left-color': 'var(--stroke-destructive)',
  },
  '.border-l-destructive-secondary': {
    'border-left-color': 'var(--stroke-destructive-secondary)',
  },
  '.border-l-destructive-tertiary': {
    'border-left-color': 'var(--stroke-destructive-tertiary)',
  },
  '.border-l-success': {
    'border-left-color': 'var(--stroke-success)',
  },
  '.border-l-success-secondary': {
    'border-left-color': 'var(--stroke-success-secondary)',
  },
  '.border-l-success-tertiary': {
    'border-left-color': 'var(--stroke-success-tertiary)',
  },
  '.border-l-error': {
    'border-left-color': 'var(--stroke-error)',
  },
  '.border-l-error-secondary': {
    'border-left-color': 'var(--stroke-error-secondary)',
  },
  '.border-l-error-tertiary': {
    'border-left-color': 'var(--stroke-error-tertiary)',
  },
  '.border-l-notice': {
    'border-left-color': 'var(--stroke-notice)',
  },
  '.border-l-notice-secondary': {
    'border-left-color': 'var(--stroke-notice-secondary)',
  },
  '.border-l-notice-tertiary': {
    'border-left-color': 'var(--stroke-notice-tertiary)',
  },
  '.border-r-default': {
    'border-right-color': 'var(--stroke-default)',
  },
  '.border-r-secondary': {
    'border-right-color': 'var(--stroke-secondary)',
  },
  '.border-r-tertiary': {
    'border-right-color': 'var(--stroke-tertiary)',
  },
  '.border-r-raise': {
    'border-right-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.border-r-surface': {
    'border-right-color': 'var(--stroke-surface)',
  },
  '.border-r-accent': {
    'border-right-color': 'var(--stroke-accent)',
  },
  '.border-r-accent-secondary': {
    'border-right-color': 'var(--stroke-accent-secondary)',
  },
  '.border-r-accent-tertiary': {
    'border-right-color': 'var(--stroke-accent-tertiary)',
  },
  '.border-r-destructive': {
    'border-right-color': 'var(--stroke-destructive)',
  },
  '.border-r-destructive-secondary': {
    'border-right-color': 'var(--stroke-destructive-secondary)',
  },
  '.border-r-destructive-tertiary': {
    'border-right-color': 'var(--stroke-destructive-tertiary)',
  },
  '.border-r-success': {
    'border-right-color': 'var(--stroke-success)',
  },
  '.border-r-success-secondary': {
    'border-right-color': 'var(--stroke-success-secondary)',
  },
  '.border-r-success-tertiary': {
    'border-right-color': 'var(--stroke-success-tertiary)',
  },
  '.border-r-error': {
    'border-right-color': 'var(--stroke-error)',
  },
  '.border-r-error-secondary': {
    'border-right-color': 'var(--stroke-error-secondary)',
  },
  '.border-r-error-tertiary': {
    'border-right-color': 'var(--stroke-error-tertiary)',
  },
  '.border-r-notice': {
    'border-right-color': 'var(--stroke-notice)',
  },
  '.border-r-notice-secondary': {
    'border-right-color': 'var(--stroke-notice-secondary)',
  },
  '.border-r-notice-tertiary': {
    'border-right-color': 'var(--stroke-notice-tertiary)',
  },
  '.border-t-default': {
    'border-top-color': 'var(--stroke-default)',
  },
  '.border-t-secondary': {
    'border-top-color': 'var(--stroke-secondary)',
  },
  '.border-t-tertiary': {
    'border-top-color': 'var(--stroke-tertiary)',
  },
  '.border-t-raise': {
    'border-top-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.border-t-surface': {
    'border-top-color': 'var(--stroke-surface)',
  },
  '.border-t-accent': {
    'border-top-color': 'var(--stroke-accent)',
  },
  '.border-t-accent-secondary': {
    'border-top-color': 'var(--stroke-accent-secondary)',
  },
  '.border-t-accent-tertiary': {
    'border-top-color': 'var(--stroke-accent-tertiary)',
  },
  '.border-t-destructive': {
    'border-top-color': 'var(--stroke-destructive)',
  },
  '.border-t-destructive-secondary': {
    'border-top-color': 'var(--stroke-destructive-secondary)',
  },
  '.border-t-destructive-tertiary': {
    'border-top-color': 'var(--stroke-destructive-tertiary)',
  },
  '.border-t-success': {
    'border-top-color': 'var(--stroke-success)',
  },
  '.border-t-success-secondary': {
    'border-top-color': 'var(--stroke-success-secondary)',
  },
  '.border-t-success-tertiary': {
    'border-top-color': 'var(--stroke-success-tertiary)',
  },
  '.border-t-error': {
    'border-top-color': 'var(--stroke-error)',
  },
  '.border-t-error-secondary': {
    'border-top-color': 'var(--stroke-error-secondary)',
  },
  '.border-t-error-tertiary': {
    'border-top-color': 'var(--stroke-error-tertiary)',
  },
  '.border-t-notice': {
    'border-top-color': 'var(--stroke-notice)',
  },
  '.border-t-notice-secondary': {
    'border-top-color': 'var(--stroke-notice-secondary)',
  },
  '.border-t-notice-tertiary': {
    'border-top-color': 'var(--stroke-notice-tertiary)',
  },
  '.border-b-default': {
    'border-bottom-color': 'var(--stroke-default)',
  },
  '.border-b-secondary': {
    'border-bottom-color': 'var(--stroke-secondary)',
  },
  '.border-b-tertiary': {
    'border-bottom-color': 'var(--stroke-tertiary)',
  },
  '.border-b-raise': {
    'border-bottom-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.border-b-surface': {
    'border-bottom-color': 'var(--stroke-surface)',
  },
  '.border-b-accent': {
    'border-bottom-color': 'var(--stroke-accent)',
  },
  '.border-b-accent-secondary': {
    'border-bottom-color': 'var(--stroke-accent-secondary)',
  },
  '.border-b-accent-tertiary': {
    'border-bottom-color': 'var(--stroke-accent-tertiary)',
  },
  '.border-b-destructive': {
    'border-bottom-color': 'var(--stroke-destructive)',
  },
  '.border-b-destructive-secondary': {
    'border-bottom-color': 'var(--stroke-destructive-secondary)',
  },
  '.border-b-destructive-tertiary': {
    'border-bottom-color': 'var(--stroke-destructive-tertiary)',
  },
  '.border-b-success': {
    'border-bottom-color': 'var(--stroke-success)',
  },
  '.border-b-success-secondary': {
    'border-bottom-color': 'var(--stroke-success-secondary)',
  },
  '.border-b-success-tertiary': {
    'border-bottom-color': 'var(--stroke-success-tertiary)',
  },
  '.border-b-error': {
    'border-bottom-color': 'var(--stroke-error)',
  },
  '.border-b-error-secondary': {
    'border-bottom-color': 'var(--stroke-error-secondary)',
  },
  '.border-b-error-tertiary': {
    'border-bottom-color': 'var(--stroke-error-tertiary)',
  },
  '.border-b-notice': {
    'border-bottom-color': 'var(--stroke-notice)',
  },
  '.border-b-notice-secondary': {
    'border-bottom-color': 'var(--stroke-notice-secondary)',
  },
  '.border-b-notice-tertiary': {
    'border-bottom-color': 'var(--stroke-notice-tertiary)',
  },
  '.border-x-default': {
    'border-left-color': 'var(--stroke-default)',
    'border-right-color': 'var(--stroke-default)',
  },
  '.border-x-secondary': {
    'border-left-color': 'var(--stroke-secondary)',
    'border-right-color': 'var(--stroke-secondary)',
  },
  '.border-x-tertiary': {
    'border-left-color': 'var(--stroke-tertiary)',
    'border-right-color': 'var(--stroke-tertiary)',
  },
  '.border-x-raise': {
    'border-left-color': 'var(--stroke-raise)',
    'border-right-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.border-x-surface': {
    'border-left-color': 'var(--stroke-surface)',
    'border-right-color': 'var(--stroke-surface)',
  },
  '.border-x-accent': {
    'border-left-color': 'var(--stroke-accent)',
    'border-right-color': 'var(--stroke-accent)',
  },
  '.border-x-accent-secondary': {
    'border-left-color': 'var(--stroke-accent-secondary)',
    'border-right-color': 'var(--stroke-accent-secondary)',
  },
  '.border-x-accent-tertiary': {
    'border-left-color': 'var(--stroke-accent-tertiary)',
    'border-right-color': 'var(--stroke-accent-tertiary)',
  },
  '.border-x-destructive': {
    'border-left-color': 'var(--stroke-destructive)',
    'border-right-color': 'var(--stroke-destructive)',
  },
  '.border-x-destructive-secondary': {
    'border-left-color': 'var(--stroke-destructive-secondary)',
    'border-right-color': 'var(--stroke-destructive-secondary)',
  },
  '.border-x-destructive-tertiary': {
    'border-left-color': 'var(--stroke-destructive-tertiary)',
    'border-right-color': 'var(--stroke-destructive-tertiary)',
  },
  '.border-x-success': {
    'border-left-color': 'var(--stroke-success)',
    'border-right-color': 'var(--stroke-success)',
  },
  '.border-x-success-secondary': {
    'border-left-color': 'var(--stroke-success-secondary)',
    'border-right-color': 'var(--stroke-success-secondary)',
  },
  '.border-x-success-tertiary': {
    'border-left-color': 'var(--stroke-success-tertiary)',
    'border-right-color': 'var(--stroke-success-tertiary)',
  },
  '.border-x-error': {
    'border-left-color': 'var(--stroke-error)',
    'border-right-color': 'var(--stroke-error)',
  },
  '.border-x-error-secondary': {
    'border-left-color': 'var(--stroke-error-secondary)',
    'border-right-color': 'var(--stroke-error-secondary)',
  },
  '.border-x-error-tertiary': {
    'border-left-color': 'var(--stroke-error-tertiary)',
    'border-right-color': 'var(--stroke-error-tertiary)',
  },
  '.border-x-notice': {
    'border-left-color': 'var(--stroke-notice)',
    'border-right-color': 'var(--stroke-notice)',
  },
  '.border-x-notice-secondary': {
    'border-left-color': 'var(--stroke-notice-secondary)',
    'border-right-color': 'var(--stroke-notice-secondary)',
  },
  '.border-x-notice-tertiary': {
    'border-left-color': 'var(--stroke-notice-tertiary)',
    'border-right-color': 'var(--stroke-notice-tertiary)',
  },
  '.border-y-default': {
    'border-top-color': 'var(--stroke-default)',
    'border-bottom-color': 'var(--stroke-default)',
  },
  '.border-y-secondary': {
    'border-top-color': 'var(--stroke-secondary)',
    'border-bottom-color': 'var(--stroke-secondary)',
  },
  '.border-y-tertiary': {
    'border-top-color': 'var(--stroke-tertiary)',
    'border-bottom-color': 'var(--stroke-tertiary)',
  },
  '.border-y-raise': {
    'border-top-color': 'var(--stroke-raise)',
    'border-bottom-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.border-y-surface': {
    'border-top-color': 'var(--stroke-surface)',
    'border-bottom-color': 'var(--stroke-surface)',
  },
  '.border-y-accent': {
    'border-top-color': 'var(--stroke-accent)',
    'border-bottom-color': 'var(--stroke-accent)',
  },
  '.border-y-accent-secondary': {
    'border-top-color': 'var(--stroke-accent-secondary)',
    'border-bottom-color': 'var(--stroke-accent-secondary)',
  },
  '.border-y-accent-tertiary': {
    'border-top-color': 'var(--stroke-accent-tertiary)',
    'border-bottom-color': 'var(--stroke-accent-tertiary)',
  },
  '.border-y-destructive': {
    'border-top-color': 'var(--stroke-destructive)',
    'border-bottom-color': 'var(--stroke-destructive)',
  },
  '.border-y-destructive-secondary': {
    'border-top-color': 'var(--stroke-destructive-secondary)',
    'border-bottom-color': 'var(--stroke-destructive-secondary)',
  },
  '.border-y-destructive-tertiary': {
    'border-top-color': 'var(--stroke-destructive-tertiary)',
    'border-bottom-color': 'var(--stroke-destructive-tertiary)',
  },
  '.border-y-success': {
    'border-top-color': 'var(--stroke-success)',
    'border-bottom-color': 'var(--stroke-success)',
  },
  '.border-y-success-secondary': {
    'border-top-color': 'var(--stroke-success-secondary)',
    'border-bottom-color': 'var(--stroke-success-secondary)',
  },
  '.border-y-success-tertiary': {
    'border-top-color': 'var(--stroke-success-tertiary)',
    'border-bottom-color': 'var(--stroke-success-tertiary)',
  },
  '.border-y-error': {
    'border-top-color': 'var(--stroke-error)',
    'border-bottom-color': 'var(--stroke-error)',
  },
  '.border-y-error-secondary': {
    'border-top-color': 'var(--stroke-error-secondary)',
    'border-bottom-color': 'var(--stroke-error-secondary)',
  },
  '.border-y-error-tertiary': {
    'border-top-color': 'var(--stroke-error-tertiary)',
    'border-bottom-color': 'var(--stroke-error-tertiary)',
  },
  '.border-y-notice': {
    'border-top-color': 'var(--stroke-notice)',
    'border-bottom-color': 'var(--stroke-notice)',
  },
  '.border-y-notice-secondary': {
    'border-top-color': 'var(--stroke-notice-secondary)',
    'border-bottom-color': 'var(--stroke-notice-secondary)',
  },
  '.border-y-notice-tertiary': {
    'border-top-color': 'var(--stroke-notice-tertiary)',
    'border-bottom-color': 'var(--stroke-notice-tertiary)',
  },
  '.ring-default': {
    '--tw-ring-color': 'var(--stroke-default)',
  },
  '.ring-secondary': {
    '--tw-ring-color': 'var(--stroke-secondary)',
  },
  '.ring-tertiary': {
    '--tw-ring-color': 'var(--stroke-tertiary)',
  },
  '.ring-raise': {
    '--tw-ring-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.ring-surface': {
    '--tw-ring-color': 'var(--stroke-surface)',
  },
  '.ring-accent': {
    '--tw-ring-color': 'var(--stroke-accent)',
  },
  '.ring-accent-secondary': {
    '--tw-ring-color': 'var(--stroke-accent-secondary)',
  },
  '.ring-accent-tertiary': {
    '--tw-ring-color': 'var(--stroke-accent-tertiary)',
  },
  '.ring-destructive': {
    '--tw-ring-color': 'var(--stroke-destructive)',
  },
  '.ring-destructive-secondary': {
    '--tw-ring-color': 'var(--stroke-destructive-secondary)',
  },
  '.ring-destructive-tertiary': {
    '--tw-ring-color': 'var(--stroke-destructive-tertiary)',
  },
  '.ring-success': {
    '--tw-ring-color': 'var(--stroke-success)',
  },
  '.ring-success-secondary': {
    '--tw-ring-color': 'var(--stroke-success-secondary)',
  },
  '.ring-success-tertiary': {
    '--tw-ring-color': 'var(--stroke-success-tertiary)',
  },
  '.ring-error': {
    '--tw-ring-color': 'var(--stroke-error)',
  },
  '.ring-error-secondary': {
    '--tw-ring-color': 'var(--stroke-error-secondary)',
  },
  '.ring-error-tertiary': {
    '--tw-ring-color': 'var(--stroke-error-tertiary)',
  },
  '.ring-notice': {
    '--tw-ring-color': 'var(--stroke-notice)',
  },
  '.ring-notice-secondary': {
    '--tw-ring-color': 'var(--stroke-notice-secondary)',
  },
  '.ring-notice-tertiary': {
    '--tw-ring-color': 'var(--stroke-notice-tertiary)',
  },
  '.outline-default': {
    'outline-color': 'var(--stroke-default)',
  },
  '.outline-secondary': {
    'outline-color': 'var(--stroke-secondary)',
  },
  '.outline-tertiary': {
    'outline-color': 'var(--stroke-tertiary)',
  },
  '.outline-raise': {
    'outline-color': 'var(--stroke-raise)',
  },
  '/* Matches the default surface color */ \n.outline-surface': {
    'outline-color': 'var(--stroke-surface)',
  },
  '.outline-accent': {
    'outline-color': 'var(--stroke-accent)',
  },
  '.outline-accent-secondary': {
    'outline-color': 'var(--stroke-accent-secondary)',
  },
  '.outline-accent-tertiary': {
    'outline-color': 'var(--stroke-accent-tertiary)',
  },
  '.outline-destructive': {
    'outline-color': 'var(--stroke-destructive)',
  },
  '.outline-destructive-secondary': {
    'outline-color': 'var(--stroke-destructive-secondary)',
  },
  '.outline-destructive-tertiary': {
    'outline-color': 'var(--stroke-destructive-tertiary)',
  },
  '.outline-success': {
    'outline-color': 'var(--stroke-success)',
  },
  '.outline-success-secondary': {
    'outline-color': 'var(--stroke-success-secondary)',
  },
  '.outline-success-tertiary': {
    'outline-color': 'var(--stroke-success-tertiary)',
  },
  '.outline-error': {
    'outline-color': 'var(--stroke-error)',
  },
  '.outline-error-secondary': {
    'outline-color': 'var(--stroke-error-secondary)',
  },
  '.outline-error-tertiary': {
    'outline-color': 'var(--stroke-error-tertiary)',
  },
  '.outline-notice': {
    'outline-color': 'var(--stroke-notice)',
  },
  '.outline-notice-secondary': {
    'outline-color': 'var(--stroke-notice-secondary)',
  },
  '.outline-notice-tertiary': {
    'outline-color': 'var(--stroke-notice-tertiary)',
  },
  '.chart-fill-area-primary': {
    fill: 'var(--chart-fill-area-primary)',
  },
  '.chart-fill-area-secondary': {
    fill: 'var(--chart-fill-area-secondary)',
  },
  '.chart-fill-area-tertiary': {
    fill: 'var(--chart-fill-area-tertiary)',
  },
  '.chart-fill-area-quaternary': {
    fill: 'var(--chart-fill-area-quaternary)',
  },
  '.chart-fill-item-primary': {
    fill: 'var(--chart-fill-item-primary)',
  },
  '.chart-fill-item-secondary': {
    fill: 'var(--chart-fill-item-secondary)',
  },
  '.chart-fill-item-tertiary': {
    fill: 'var(--chart-fill-item-tertiary)',
  },
  '.chart-fill-item-quaternary': {
    fill: 'var(--chart-fill-item-quaternary)',
  },
  '.chart-fill-error-primary': {
    fill: 'var(--chart-fill-error-primary)',
  },
  '.chart-fill-error-secondary': {
    fill: 'var(--chart-fill-error-secondary)',
  },
  '.chart-fill-error-tertiary': {
    fill: 'var(--chart-fill-error-tertiary)',
  },
  '.chart-fill-error-quaternary': {
    fill: 'var(--chart-fill-error-quaternary)',
  },
  '.chart-fill-inactive': {
    fill: 'var(--chart-fill-inactive)',
  },
  '.chart-stroke-line': {
    stroke: 'var(--chart-stroke-line)',
  },
  '.chart-stroke-line-secondary': {
    stroke: 'var(--chart-stroke-line-secondary)',
  },
  '.chart-stroke-line-tertiary': {
    stroke: 'var(--chart-stroke-line-tertiary)',
  },
  '.chart-stroke-line-quaternary': {
    stroke: 'var(--chart-stroke-line-quaternary)',
  },
  '.chart-stroke-y-axis': {
    stroke: 'var(--chart-stroke-y-axis)',
  },
  '/* Used as a stroke in conjuction with a fill. For discrete shapes e.g. bar charts; pie charts; tree maps. */ \n.chart-stroke-item':
    {
      stroke: 'var(--chart-stroke-item)',
    },
  '.chart-stroke-item-inactive': {
    stroke: 'var(--chart-stroke-item-inactive)',
  },
  '.chart-stroke-error': {
    stroke: 'var(--chart-stroke-error)',
  },
}

module.exports.borderRadiusTokens = {
  DEFAULT: 'var(--border-radius)',
  lg: 'var(--border-radius-lg)',
  full: 'var(--border-radius-full)',
}
