/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

// generated by tools/gen_api.ts from the Nexus source in omicron.
// do not update manually. see docs/update-pinned-api.md

export const nexusCsp =
  "default-src 'self'; style-src 'unsafe-inline' 'self'; frame-src 'none'; object-src 'none'; form-action 'none'; frame-ancestors 'none'"

/** Dropshot path templates that Nexus serves the console's index.html on */
export const nexusConsoleRoutes = [
  '/',
  '/access',
  '/device/success',
  '/device/verify',
  '/images/{path:.*}',
  '/login/{silo_name}/local',
  '/login/{silo_name}/saml/{provider_name}',
  '/lookup/{path:.*}',
  '/projects-new',
  '/projects/{path:.*}',
  '/settings/{path:.*}',
  '/system/{path:.*}',
  '/utilization',
]
