/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */
import type { TimeseriesSchema } from '@oxide/api'

import type { Json } from './json-type'

/**
 * Snapshot from dogfood, as schemas are pretty darn stable. Trimmed down to a
 * smaller set to represent the variety of datum_type.
 */
export const timeseriesSchemas: Json<TimeseriesSchema>[] = [
  {
    timeseries_name: 'collection_target:cpus_provisioned',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'i64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2023-10-25T23:05:04.909050887Z',
  },
  {
    timeseries_name: 'crucible_upstairs:activated',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'upstairs_uuid',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'cumulative_i64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2023-10-25T23:04:34.899663499Z',
  },
  {
    timeseries_name: 'database_transaction:retry_data',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'attempt',
        field_type: 'u32',
        source: 'metric',
        description: '',
      },
      {
        name: 'name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'f64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2023-12-09T05:05:12.777325080Z',
  },
  {
    timeseries_name: 'ddm_router:originated_tunnel_endpoints',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'hostname',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'u64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-03-22T06:41:04.468869678Z',
  },
  {
    timeseries_name: 'hardware_component:amd_cpu_tctl',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'chassis_kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'component_id',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'component_kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'description',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'gateway_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'hubris_archive_id',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sensor',
        field_type: 'string',
        source: 'metric',
        description: '',
      },
      {
        name: 'slot',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'f32',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-09-26T20:54:40.780650780Z',
  },
  {
    timeseries_name: 'hardware_component:fan_speed',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'chassis_kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'component_id',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'component_kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'description',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'gateway_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'hubris_archive_id',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sensor',
        field_type: 'string',
        source: 'metric',
        description: '',
      },
      {
        name: 'slot',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'f32',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-08-27T02:18:06.071093138Z',
  },
  {
    timeseries_name: 'hardware_component:sensor_error_count',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'chassis_kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'component_id',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'component_kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'description',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'error',
        field_type: 'string',
        source: 'metric',
        description: '',
      },
      {
        name: 'gateway_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'hubris_archive_id',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sensor',
        field_type: 'string',
        source: 'metric',
        description: '',
      },
      {
        name: 'sensor_kind',
        field_type: 'string',
        source: 'metric',
        description: '',
      },
      {
        name: 'slot',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'cumulative_u64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-08-27T02:18:06.038148045Z',
  },
  {
    timeseries_name: 'hardware_component:temperature',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'chassis_kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'chassis_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'component_id',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'component_kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'description',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'gateway_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'hubris_archive_id',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sensor',
        field_type: 'string',
        source: 'metric',
        description: '',
      },
      {
        name: 'slot',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'f32',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-08-27T02:18:06.044202257Z',
  },
  {
    timeseries_name: 'sled_data_link:bytes_received',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'link_name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'zone_name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'cumulative_u64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-08-14T03:24:34.149372848Z',
  },
  {
    timeseries_name: 'sled_data_link:bytes_sent',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'link_name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'zone_name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'cumulative_u64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-08-14T03:24:34.232414065Z',
  },
  {
    timeseries_name: 'sled_data_link:errors_received',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'link_name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'zone_name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'cumulative_u64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-08-14T03:24:34.050086881Z',
  },
  {
    timeseries_name: 'sled_data_link:errors_sent',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'link_name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'zone_name',
        field_type: 'string',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'cumulative_u64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-08-14T03:24:34.092318117Z',
  },
  {
    timeseries_name: 'switch_data_link:fec_high_symbol_errors',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'asic_fab',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'asic_lot',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'asic_wafer',
        field_type: 'u8',
        source: 'target',
        description: '',
      },
      {
        name: 'asic_wafer_loc_x',
        field_type: 'i16',
        source: 'target',
        description: '',
      },
      {
        name: 'asic_wafer_loc_y',
        field_type: 'i16',
        source: 'target',
        description: '',
      },
      {
        name: 'kind',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'link_id',
        field_type: 'u8',
        source: 'metric',
        description: '',
      },
      {
        name: 'model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'network',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'port_id',
        field_type: 'string',
        source: 'metric',
        description: '',
      },
      {
        name: 'rack_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'sled_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'switch_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'switch_model',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'switch_revision',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'switch_serial',
        field_type: 'string',
        source: 'target',
        description: '',
      },
      {
        name: 'switch_slot',
        field_type: 'u16',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'bool',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2025-02-14T22:29:39.720562272Z',
  },
  {
    timeseries_name: 'virtual_disk:io_latency',
    description: {
      target: '',
      metric: '',
    },
    field_schema: [
      {
        name: 'attached_instance_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'block_size',
        field_type: 'u32',
        source: 'target',
        description: '',
      },
      {
        name: 'disk_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'io_kind',
        field_type: 'string',
        source: 'metric',
        description: '',
      },
      {
        name: 'project_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
      {
        name: 'silo_id',
        field_type: 'uuid',
        source: 'target',
        description: '',
      },
    ],
    datum_type: 'histogram_u64',
    version: 1,
    authz_scope: 'fleet',
    units: 'none',
    created: '2024-09-12T18:07:20.754569807Z',
  },
]
