# fly.toml app configuration file generated for proud-pine-2297 on 2023-07-10T23:50:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proud-pine-2297"
primary_region = "ord"

[http_service]
  internal_port = 4507
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
