import { pb } from './path-builder'

// params can be the same for all of them because they only use what they need
const params = {
  project: 'b',
  instance: 'c',
  vpc: 'd',
  silo: 's',
  version: 'v',
}

test('path builder', () => {
  expect(Object.fromEntries(Object.entries(pb).map(([key, fn]) => [key, fn(params)])))
    .toMatchInlineSnapshot(`
      {
        "deviceSuccess": "/device/success",
        "diskInventory": "/sys/inventory/disks",
        "diskNew": "/orgs/abc/projects/b/disks-new",
        "disks": "/orgs/abc/projects/b/disks",
        "instance": "/orgs/abc/projects/b/instances/c",
        "instanceConnect": "/orgs/abc/projects/b/instances/c/connect",
        "instanceMetrics": "/orgs/abc/projects/b/instances/c/metrics",
        "instanceNew": "/orgs/abc/projects/b/instances-new",
        "instancePage": "/orgs/abc/projects/b/instances/c/storage",
        "instanceStorage": "/orgs/abc/projects/b/instances/c/storage",
        "instances": "/orgs/abc/projects/b/instances",
        "nics": "/orgs/abc/projects/b/instances/c/network-interfaces",
        "org": "/orgs/abc",
        "orgAccess": "/orgs/abc/access",
        "orgEdit": "/orgs/abc/edit",
        "orgNew": "/orgs-new",
        "orgs": "/orgs",
        "profile": "/settings/profile",
        "project": "/orgs/abc/projects/b",
        "projectAccess": "/orgs/abc/projects/b/access",
        "projectEdit": "/orgs/abc/projects/b/edit",
        "projectImages": "/orgs/abc/projects/b/images",
        "projectNew": "/orgs/abc/projects-new",
        "projects": "/orgs/abc/projects",
        "rackInventory": "/sys/inventory/racks",
        "serialConsole": "/orgs/abc/projects/b/instances/c/serial-console",
        "settings": "/settings",
        "silo": "/sys/silos/s",
        "siloAccess": "/access",
        "siloIdpNew": "/sys/silos/s/idps-new",
        "siloNew": "/sys/silos-new",
        "siloUtilization": "/utilization",
        "silos": "/sys/silos",
        "sledInventory": "/sys/inventory/sleds",
        "snapshotNew": "/orgs/abc/projects/b/snapshots-new",
        "snapshots": "/orgs/abc/projects/b/snapshots",
        "sshKeyNew": "/settings/ssh-keys-new",
        "sshKeys": "/settings/ssh-keys",
        "system": "/sys",
        "systemHealth": "/sys/health",
        "systemIssues": "/sys/issues",
        "systemNetworking": "/sys/networking",
        "systemSettings": "/sys/settings",
        "systemUpdateDetail": "/sys/update/updates/v",
        "systemUpdateHistory": "/sys/update/history",
        "systemUpdates": "/sys/update/updates",
        "systemUtilization": "/sys/utilization",
        "updateableComponents": "/sys/update/components",
        "vpc": "/orgs/abc/projects/b/vpcs/d",
        "vpcEdit": "/orgs/abc/projects/b/vpcs/d/edit",
        "vpcNew": "/orgs/abc/projects/b/vpcs-new",
        "vpcs": "/orgs/abc/projects/b/vpcs",
      }
    `)
})
