/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum ActionErrorAnyOf {
  InjectedError = 'InjectedError',
}

export function ActionErrorAnyOfFromJSON(json: any): ActionErrorAnyOf {
  return ActionErrorAnyOfFromJSONTyped(json, false)
}

export function ActionErrorAnyOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ActionErrorAnyOf {
  return json as ActionErrorAnyOf
}

export function ActionErrorAnyOfToJSON(value?: ActionErrorAnyOf | null): any {
  return value as any
}
