/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ActionErrorAnyOf1ActionFailed
 */
export interface ActionErrorAnyOf1ActionFailed {
  /**
   *
   * @type {any}
   * @memberof ActionErrorAnyOf1ActionFailed
   */
  sourceError: any | null
}

export function ActionErrorAnyOf1ActionFailedFromJSON(
  json: any
): ActionErrorAnyOf1ActionFailed {
  return ActionErrorAnyOf1ActionFailedFromJSONTyped(json, false)
}

export function ActionErrorAnyOf1ActionFailedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ActionErrorAnyOf1ActionFailed {
  if (json === undefined || json === null) {
    return json
  }
  return {
    sourceError: json['source_error'],
  }
}

export function ActionErrorAnyOf1ActionFailedToJSON(
  value?: ActionErrorAnyOf1ActionFailed | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    source_error: value.sourceError,
  }
}
