/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ActionErrorAnyOf2DeserializeFailed,
  ActionErrorAnyOf2DeserializeFailedFromJSON,
  ActionErrorAnyOf2DeserializeFailedFromJSONTyped,
  ActionErrorAnyOf2DeserializeFailedToJSON,
} from './'

/**
 * The framework failed to serialize the saga parameters, an action's successful result, or an action's error.
 * @export
 * @interface ActionErrorAnyOf3
 */
export interface ActionErrorAnyOf3 {
  /**
   *
   * @type {ActionErrorAnyOf2DeserializeFailed}
   * @memberof ActionErrorAnyOf3
   */
  serializeFailed: ActionErrorAnyOf2DeserializeFailed
}

export function ActionErrorAnyOf3FromJSON(json: any): ActionErrorAnyOf3 {
  return ActionErrorAnyOf3FromJSONTyped(json, false)
}

export function ActionErrorAnyOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ActionErrorAnyOf3 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    serializeFailed: ActionErrorAnyOf2DeserializeFailedFromJSON(
      json['SerializeFailed']
    ),
  }
}

export function ActionErrorAnyOf3ToJSON(value?: ActionErrorAnyOf3 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    SerializeFailed: ActionErrorAnyOf2DeserializeFailedToJSON(
      value.serializeFailed
    ),
  }
}
