/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Disk is being attached to the given Instance
 * @export
 * @interface ApiDiskStateAnyOf1
 */
export interface ApiDiskStateAnyOf1 {
  /**
   *
   * @type {string}
   * @memberof ApiDiskStateAnyOf1
   */
  attaching: string
}

export function ApiDiskStateAnyOf1FromJSON(json: any): ApiDiskStateAnyOf1 {
  return ApiDiskStateAnyOf1FromJSONTyped(json, false)
}

export function ApiDiskStateAnyOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiDiskStateAnyOf1 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    attaching: json['attaching'],
  }
}

export function ApiDiskStateAnyOf1ToJSON(
  value?: ApiDiskStateAnyOf1 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    attaching: value.attaching,
  }
}
