/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiDiskState,
  ApiDiskStateFromJSON,
  ApiDiskStateFromJSONTyped,
  ApiDiskStateToJSON,
} from './'

/**
 * Client view of an [`ApiDisk`]
 * @export
 * @interface ApiDiskView
 */
export interface ApiDiskView {
  /**
   * human-readable free-form text about a resource
   * @type {string}
   * @memberof ApiDiskView
   */
  description: string
  /**
   *
   * @type {string}
   * @memberof ApiDiskView
   */
  devicePath: string
  /**
   * unique, immutable, system-controlled identifier for each resource
   * @type {string}
   * @memberof ApiDiskView
   */
  id: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof ApiDiskView
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof ApiDiskView
   */
  projectId: string
  /**
   * A count of bytes, typically used either for memory or storage capacity
   *
   * The maximum supported byte count is [`i64::MAX`].  This makes it somewhat inconvenient to define constructors: a u32 constructor can be infallible, but an i64 constructor can fail (if the value is negative) and a u64 constructor can fail (if the value is larger than i64::MAX).  We provide all of these for consumers' convenience.
   * @type {number}
   * @memberof ApiDiskView
   */
  size: number
  /**
   *
   * @type {string}
   * @memberof ApiDiskView
   */
  snapshotId?: string
  /**
   *
   * @type {ApiDiskState}
   * @memberof ApiDiskView
   */
  state: ApiDiskState
  /**
   * timestamp when this resource was created
   * @type {Date}
   * @memberof ApiDiskView
   */
  timeCreated: Date
  /**
   * timestamp when this resource was last modified
   * @type {Date}
   * @memberof ApiDiskView
   */
  timeModified: Date
}

export function ApiDiskViewFromJSON(json: any): ApiDiskView {
  return ApiDiskViewFromJSONTyped(json, false)
}

export function ApiDiskViewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiDiskView {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    devicePath: json['devicePath'],
    id: json['id'],
    name: json['name'],
    projectId: json['projectId'],
    size: json['size'],
    snapshotId: !exists(json, 'snapshotId') ? undefined : json['snapshotId'],
    state: ApiDiskStateFromJSON(json['state']),
    timeCreated: new Date(json['timeCreated']),
    timeModified: new Date(json['timeModified']),
  }
}

export function ApiDiskViewToJSON(value?: ApiDiskView | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    devicePath: value.devicePath,
    id: value.id,
    name: value.name,
    projectId: value.projectId,
    size: value.size,
    snapshotId: value.snapshotId,
    state: ApiDiskStateToJSON(value.state),
    timeCreated: value.timeCreated.toISOString(),
    timeModified: value.timeModified.toISOString(),
  }
}
