/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiDiskView,
  ApiDiskViewFromJSON,
  ApiDiskViewFromJSONTyped,
  ApiDiskViewToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface ApiDiskViewResultsPage
 */
export interface ApiDiskViewResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<ApiDiskView>}
   * @memberof ApiDiskViewResultsPage
   */
  items: Array<ApiDiskView>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof ApiDiskViewResultsPage
   */
  nextPage?: string
}

export function ApiDiskViewResultsPageFromJSON(
  json: any
): ApiDiskViewResultsPage {
  return ApiDiskViewResultsPageFromJSONTyped(json, false)
}

export function ApiDiskViewResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiDiskViewResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(ApiDiskViewFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function ApiDiskViewResultsPageToJSON(
  value?: ApiDiskViewResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(ApiDiskViewToJSON),
    next_page: value.nextPage,
  }
}
