/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Create-time parameters for an [`ApiDisk`]
 * @export
 * @interface ApiDiskCreateParams
 */
export interface ApiDiskCreateParams {
  /**
   *
   * @type {string}
   * @memberof ApiDiskCreateParams
   */
  description: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof ApiDiskCreateParams
   */
  name: string
  /**
   * A count of bytes, typically used either for memory or storage capacity
   *
   * The maximum supported byte count is [`i64::MAX`].  This makes it somewhat inconvenient to define constructors: a u32 constructor can be infallible, but an i64 constructor can fail (if the value is negative) and a u64 constructor can fail (if the value is larger than i64::MAX).  We provide all of these for consumers' convenience.
   * @type {number}
   * @memberof ApiDiskCreateParams
   */
  size: number
  /**
   * id for snapshot from which the Disk should be created, if any
   * @type {string}
   * @memberof ApiDiskCreateParams
   */
  snapshotId?: string
}

export function ApiDiskCreateParamsFromJSON(json: any): ApiDiskCreateParams {
  return ApiDiskCreateParamsFromJSONTyped(json, false)
}

export function ApiDiskCreateParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiDiskCreateParams {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    name: json['name'],
    size: json['size'],
    snapshotId: !exists(json, 'snapshotId') ? undefined : json['snapshotId'],
  }
}

export function ApiDiskCreateParamsToJSON(
  value?: ApiDiskCreateParams | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    name: value.name,
    size: value.size,
    snapshotId: value.snapshotId,
  }
}
