/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiDiskState,
  ApiDiskStateFromJSON,
  ApiDiskStateFromJSONTyped,
  ApiDiskStateToJSON,
} from './'

/**
 * Describes a Disk's attachment to an Instance
 * @export
 * @interface ApiDiskAttachment1
 */
export interface ApiDiskAttachment1 {
  /**
   *
   * @type {string}
   * @memberof ApiDiskAttachment1
   */
  diskId: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof ApiDiskAttachment1
   */
  diskName: string
  /**
   *
   * @type {ApiDiskState}
   * @memberof ApiDiskAttachment1
   */
  diskState: ApiDiskState
  /**
   *
   * @type {string}
   * @memberof ApiDiskAttachment1
   */
  instanceId: string
}

export function ApiDiskAttachment1FromJSON(json: any): ApiDiskAttachment1 {
  return ApiDiskAttachment1FromJSONTyped(json, false)
}

export function ApiDiskAttachment1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiDiskAttachment1 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    diskId: json['diskId'],
    diskName: json['diskName'],
    diskState: ApiDiskStateFromJSON(json['diskState']),
    instanceId: json['instanceId'],
  }
}

export function ApiDiskAttachment1ToJSON(
  value?: ApiDiskAttachment1 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    diskId: value.diskId,
    diskName: value.diskName,
    diskState: ApiDiskStateToJSON(value.diskState),
    instanceId: value.instanceId,
  }
}
