/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiInstanceStateAnyOf1Stopping,
  ApiInstanceStateAnyOf1StoppingFromJSON,
  ApiInstanceStateAnyOf1StoppingFromJSONTyped,
  ApiInstanceStateAnyOf1StoppingToJSON,
} from './'

/**
 *
 * @export
 * @interface ApiInstanceStateAnyOf2
 */
export interface ApiInstanceStateAnyOf2 {
  /**
   *
   * @type {ApiInstanceStateAnyOf1Stopping}
   * @memberof ApiInstanceStateAnyOf2
   */
  stopped: ApiInstanceStateAnyOf1Stopping
}

export function ApiInstanceStateAnyOf2FromJSON(
  json: any
): ApiInstanceStateAnyOf2 {
  return ApiInstanceStateAnyOf2FromJSONTyped(json, false)
}

export function ApiInstanceStateAnyOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiInstanceStateAnyOf2 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    stopped: ApiInstanceStateAnyOf1StoppingFromJSON(json['stopped']),
  }
}

export function ApiInstanceStateAnyOf2ToJSON(
  value?: ApiInstanceStateAnyOf2 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    stopped: ApiInstanceStateAnyOf1StoppingToJSON(value.stopped),
  }
}
