/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiInstanceView,
  ApiInstanceViewFromJSON,
  ApiInstanceViewFromJSONTyped,
  ApiInstanceViewToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface ApiInstanceViewResultsPage
 */
export interface ApiInstanceViewResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<ApiInstanceView>}
   * @memberof ApiInstanceViewResultsPage
   */
  items: Array<ApiInstanceView>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof ApiInstanceViewResultsPage
   */
  nextPage?: string
}

export function ApiInstanceViewResultsPageFromJSON(
  json: any
): ApiInstanceViewResultsPage {
  return ApiInstanceViewResultsPageFromJSONTyped(json, false)
}

export function ApiInstanceViewResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiInstanceViewResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(ApiInstanceViewFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function ApiInstanceViewResultsPageToJSON(
  value?: ApiInstanceViewResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(ApiInstanceViewToJSON),
    next_page: value.nextPage,
  }
}
