/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Create-time parameters for an [`ApiInstance`]
 * @export
 * @interface ApiInstanceCreateParams
 */
export interface ApiInstanceCreateParams {
  /**
   * A count of bytes, typically used either for memory or storage capacity
   * @type {number}
   * @memberof ApiInstanceCreateParams
   */
  bootDiskSize: number
  /**
   *
   * @type {string}
   * @memberof ApiInstanceCreateParams
   */
  description: string
  /**
   *
   * @type {string}
   * @memberof ApiInstanceCreateParams
   */
  hostname: string
  /**
   * A count of bytes, typically used either for memory or storage capacity
   * @type {number}
   * @memberof ApiInstanceCreateParams
   */
  memory: number
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof ApiInstanceCreateParams
   */
  name: string
  /**
   * The number of CPUs in an Instance
   * @type {number}
   * @memberof ApiInstanceCreateParams
   */
  ncpus: number
}

export function ApiInstanceCreateParamsFromJSON(
  json: any
): ApiInstanceCreateParams {
  return ApiInstanceCreateParamsFromJSONTyped(json, false)
}

export function ApiInstanceCreateParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiInstanceCreateParams {
  if (json === undefined || json === null) {
    return json
  }
  return {
    bootDiskSize: json['bootDiskSize'],
    description: json['description'],
    hostname: json['hostname'],
    memory: json['memory'],
    name: json['name'],
    ncpus: json['ncpus'],
  }
}

export function ApiInstanceCreateParamsToJSON(
  value?: ApiInstanceCreateParams | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    bootDiskSize: value.bootDiskSize,
    description: value.description,
    hostname: value.hostname,
    memory: value.memory,
    name: value.name,
    ncpus: value.ncpus,
  }
}
