/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Supported set of sort modes for scanning by name only
 *
 * Currently, we only support scanning in ascending order.
 * @export
 * @enum {string}
 */
export enum ApiNameSortMode {
  NameAscending = 'name-ascending',
}

export function ApiNameSortModeFromJSON(json: any): ApiNameSortMode {
  return ApiNameSortModeFromJSONTyped(json, false)
}

export function ApiNameSortModeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiNameSortMode {
  return json as ApiNameSortMode
}

export function ApiNameSortModeToJSON(value?: ApiNameSortMode | null): any {
  return value as any
}
