/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiRackView,
  ApiRackViewFromJSON,
  ApiRackViewFromJSONTyped,
  ApiRackViewToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface ApiRackViewResultsPage
 */
export interface ApiRackViewResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<ApiRackView>}
   * @memberof ApiRackViewResultsPage
   */
  items: Array<ApiRackView>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof ApiRackViewResultsPage
   */
  nextPage?: string
}

export function ApiRackViewResultsPageFromJSON(
  json: any
): ApiRackViewResultsPage {
  return ApiRackViewResultsPageFromJSONTyped(json, false)
}

export function ApiRackViewResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiRackViewResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(ApiRackViewFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function ApiRackViewResultsPageToJSON(
  value?: ApiRackViewResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(ApiRackViewToJSON),
    next_page: value.nextPage,
  }
}
