/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiSagaStateView,
  ApiSagaStateViewFromJSON,
  ApiSagaStateViewFromJSONTyped,
  ApiSagaStateViewToJSON,
} from './'

/**
 *
 * @export
 * @interface ApiSagaView
 */
export interface ApiSagaView {
  /**
   *
   * @type {string}
   * @memberof ApiSagaView
   */
  id: string
  /**
   *
   * @type {ApiSagaStateView}
   * @memberof ApiSagaView
   */
  state: ApiSagaStateView
}

export function ApiSagaViewFromJSON(json: any): ApiSagaView {
  return ApiSagaViewFromJSONTyped(json, false)
}

export function ApiSagaViewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiSagaView {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    state: ApiSagaStateViewFromJSON(json['state']),
  }
}

export function ApiSagaViewToJSON(value?: ApiSagaView | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    state: ApiSagaStateViewToJSON(value.state),
  }
}
