/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiSagaStateViewAnyOf,
  ApiSagaStateViewAnyOfFromJSON,
  ApiSagaStateViewAnyOfFromJSONTyped,
  ApiSagaStateViewAnyOfToJSON,
  ApiSagaStateViewAnyOf1,
  ApiSagaStateViewAnyOf1FromJSON,
  ApiSagaStateViewAnyOf1FromJSONTyped,
  ApiSagaStateViewAnyOf1ToJSON,
  ApiSagaStateViewAnyOf1Done,
  ApiSagaStateViewAnyOf1DoneFromJSON,
  ApiSagaStateViewAnyOf1DoneFromJSONTyped,
  ApiSagaStateViewAnyOf1DoneToJSON,
} from './'

/**
 *
 * @export
 * @interface ApiSagaStateView
 */
export interface ApiSagaStateView {
  /**
   *
   * @type {ApiSagaStateViewAnyOf1Done}
   * @memberof ApiSagaStateView
   */
  done: ApiSagaStateViewAnyOf1Done
}

export function ApiSagaStateViewFromJSON(json: any): ApiSagaStateView {
  return ApiSagaStateViewFromJSONTyped(json, false)
}

export function ApiSagaStateViewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiSagaStateView {
  if (json === undefined || json === null) {
    return json
  }
  return {
    done: ApiSagaStateViewAnyOf1DoneFromJSON(json['done']),
  }
}

export function ApiSagaStateViewToJSON(value?: ApiSagaStateView | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    done: ApiSagaStateViewAnyOf1DoneToJSON(value.done),
  }
}
