/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum ApiSagaStateViewAnyOf {
  Running = 'running',
}

export function ApiSagaStateViewAnyOfFromJSON(
  json: any
): ApiSagaStateViewAnyOf {
  return ApiSagaStateViewAnyOfFromJSONTyped(json, false)
}

export function ApiSagaStateViewAnyOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiSagaStateViewAnyOf {
  return json as ApiSagaStateViewAnyOf
}

export function ApiSagaStateViewAnyOfToJSON(
  value?: ApiSagaStateViewAnyOf | null
): any {
  return value as any
}
