/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Client view of an [`ApiSled`]
 * @export
 * @interface ApiSledView1
 */
export interface ApiSledView1 {
  /**
   * human-readable free-form text about a resource
   * @type {string}
   * @memberof ApiSledView1
   */
  description: string
  /**
   * unique, immutable, system-controlled identifier for each resource
   * @type {string}
   * @memberof ApiSledView1
   */
  id: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof ApiSledView1
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof ApiSledView1
   */
  serviceAddress: string
  /**
   * timestamp when this resource was created
   * @type {Date}
   * @memberof ApiSledView1
   */
  timeCreated: Date
  /**
   * timestamp when this resource was last modified
   * @type {Date}
   * @memberof ApiSledView1
   */
  timeModified: Date
}

export function ApiSledView1FromJSON(json: any): ApiSledView1 {
  return ApiSledView1FromJSONTyped(json, false)
}

export function ApiSledView1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiSledView1 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    id: json['id'],
    name: json['name'],
    serviceAddress: json['serviceAddress'],
    timeCreated: new Date(json['timeCreated']),
    timeModified: new Date(json['timeModified']),
  }
}

export function ApiSledView1ToJSON(value?: ApiSledView1 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    id: value.id,
    name: value.name,
    serviceAddress: value.serviceAddress,
    timeCreated: value.timeCreated.toISOString(),
    timeModified: value.timeModified.toISOString(),
  }
}
