/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  DiskStateAnyOf,
  DiskStateAnyOfFromJSON,
  DiskStateAnyOfFromJSONTyped,
  DiskStateAnyOfToJSON,
  DiskStateAnyOf1,
  DiskStateAnyOf1FromJSON,
  DiskStateAnyOf1FromJSONTyped,
  DiskStateAnyOf1ToJSON,
  DiskStateAnyOf2,
  DiskStateAnyOf2FromJSON,
  DiskStateAnyOf2FromJSONTyped,
  DiskStateAnyOf2ToJSON,
  DiskStateAnyOf3,
  DiskStateAnyOf3FromJSON,
  DiskStateAnyOf3FromJSONTyped,
  DiskStateAnyOf3ToJSON,
  DiskStateAnyOf4,
  DiskStateAnyOf4FromJSON,
  DiskStateAnyOf4FromJSONTyped,
  DiskStateAnyOf4ToJSON,
  DiskStateAnyOf5,
  DiskStateAnyOf5FromJSON,
  DiskStateAnyOf5FromJSONTyped,
  DiskStateAnyOf5ToJSON,
  DiskStateAnyOf6,
  DiskStateAnyOf6FromJSON,
  DiskStateAnyOf6FromJSONTyped,
  DiskStateAnyOf6ToJSON,
} from './'

/**
 * State of a Disk (primarily: attached or not)
 * @export
 * @interface DiskState
 */
export interface DiskState {
  /**
   *
   * @type {string}
   * @memberof DiskState
   */
  state: DiskStateStateEnum
  /**
   *
   * @type {string}
   * @memberof DiskState
   */
  instance: string
}

/**
 * @export
 * @enum {string}
 */
export enum DiskStateStateEnum {
  Faulted = 'faulted',
}

export function DiskStateFromJSON(json: any): DiskState {
  return DiskStateFromJSONTyped(json, false)
}

export function DiskStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DiskState {
  if (json === undefined || json === null) {
    return json
  }
  return {
    state: json['state'],
    instance: json['instance'],
  }
}

export function DiskStateToJSON(value?: DiskState | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    state: value.state,
    instance: value.instance,
  }
}
