/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Create-time parameters for a [`Disk`]
 * @export
 * @interface DiskCreate
 */
export interface DiskCreate {
  /**
   *
   * @type {string}
   * @memberof DiskCreate
   */
  description: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof DiskCreate
   */
  name: string
  /**
   * size of the Disk
   * @type {number}
   * @memberof DiskCreate
   */
  size: number
  /**
   * id for snapshot from which the Disk should be created, if any
   * @type {string}
   * @memberof DiskCreate
   */
  snapshotId?: string | null
}

export function DiskCreateFromJSON(json: any): DiskCreate {
  return DiskCreateFromJSONTyped(json, false)
}

export function DiskCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DiskCreate {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    name: json['name'],
    size: json['size'],
    snapshotId: !exists(json, 'snapshotId') ? undefined : json['snapshotId'],
  }
}

export function DiskCreateToJSON(value?: DiskCreate | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    name: value.name,
    size: value.size,
    snapshotId: value.snapshotId,
  }
}
