/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  DiskState,
  DiskStateFromJSON,
  DiskStateFromJSONTyped,
  DiskStateToJSON,
} from './'

/**
 * Describes a Disk's attachment to an Instance
 * @export
 * @interface DiskAttachment
 */
export interface DiskAttachment {
  /**
   *
   * @type {string}
   * @memberof DiskAttachment
   */
  diskId: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof DiskAttachment
   */
  diskName: string
  /**
   *
   * @type {DiskState}
   * @memberof DiskAttachment
   */
  diskState: DiskState
  /**
   *
   * @type {string}
   * @memberof DiskAttachment
   */
  instanceId: string
}

export function DiskAttachmentFromJSON(json: any): DiskAttachment {
  return DiskAttachmentFromJSONTyped(json, false)
}

export function DiskAttachmentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DiskAttachment {
  if (json === undefined || json === null) {
    return json
  }
  return {
    diskId: json['diskId'],
    diskName: json['diskName'],
    diskState: DiskStateFromJSON(json['diskState']),
    instanceId: json['instanceId'],
  }
}

export function DiskAttachmentToJSON(value?: DiskAttachment | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    diskId: value.diskId,
    diskName: value.diskName,
    diskState: DiskStateToJSON(value.diskState),
    instanceId: value.instanceId,
  }
}
