/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Disk is being detached from the given Instance
 * @export
 * @interface DiskStateAnyOf4
 */
export interface DiskStateAnyOf4 {
  /**
   *
   * @type {string}
   * @memberof DiskStateAnyOf4
   */
  instance: string
  /**
   *
   * @type {string}
   * @memberof DiskStateAnyOf4
   */
  state: DiskStateAnyOf4StateEnum
}

/**
 * @export
 * @enum {string}
 */
export enum DiskStateAnyOf4StateEnum {
  Detaching = 'detaching',
}

export function DiskStateAnyOf4FromJSON(json: any): DiskStateAnyOf4 {
  return DiskStateAnyOf4FromJSONTyped(json, false)
}

export function DiskStateAnyOf4FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DiskStateAnyOf4 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    instance: json['instance'],
    state: json['state'],
  }
}

export function DiskStateAnyOf4ToJSON(value?: DiskStateAnyOf4 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    instance: value.instance,
    state: value.state,
  }
}
