/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Disk is being attached to the given Instance
 * @export
 * @interface DiskStateOneOf2
 */
export interface DiskStateOneOf2 {
  /**
   *
   * @type {string}
   * @memberof DiskStateOneOf2
   */
  instance: string
  /**
   *
   * @type {string}
   * @memberof DiskStateOneOf2
   */
  state: DiskStateOneOf2StateEnum
}

/**
 * @export
 * @enum {string}
 */
export enum DiskStateOneOf2StateEnum {
  Attaching = 'attaching',
}

export function DiskStateOneOf2FromJSON(json: any): DiskStateOneOf2 {
  return DiskStateOneOf2FromJSONTyped(json, false)
}

export function DiskStateOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DiskStateOneOf2 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    instance: json['instance'],
    state: json['state'],
  }
}

export function DiskStateOneOf2ToJSON(value?: DiskStateOneOf2 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    instance: value.instance,
    state: value.state,
  }
}
