/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Disk is unavailable
 * @export
 * @interface DiskStateOneOf6
 */
export interface DiskStateOneOf6 {
  /**
   *
   * @type {string}
   * @memberof DiskStateOneOf6
   */
  state: 'faulted'
}

export function DiskStateOneOf6FromJSON(json: any): DiskStateOneOf6 {
  return DiskStateOneOf6FromJSONTyped(json, false)
}

export function DiskStateOneOf6FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DiskStateOneOf6 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    state: json['state'],
  }
}

export function DiskStateOneOf6ToJSON(value?: DiskStateOneOf6 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    state: value.state,
  }
}
