/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Disk is being detached from the given Instance
 * @export
 * @interface DiskStateOneOf4
 */
export interface DiskStateOneOf4 {
  /**
   *
   * @type {string}
   * @memberof DiskStateOneOf4
   */
  instance: string
  /**
   *
   * @type {string}
   * @memberof DiskStateOneOf4
   */
  state: 'detaching'
}

export function DiskStateOneOf4FromJSON(json: any): DiskStateOneOf4 {
  return DiskStateOneOf4FromJSONTyped(json, false)
}

export function DiskStateOneOf4FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DiskStateOneOf4 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    instance: json['instance'],
    state: json['state'],
  }
}

export function DiskStateOneOf4ToJSON(value?: DiskStateOneOf4 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    instance: value.instance,
    state: value.state,
  }
}
