/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Disk is being detached from the given Instance
 * @export
 * @interface DiskStateAnyOf3
 */
export interface DiskStateAnyOf3 {
  /**
   *
   * @type {string}
   * @memberof DiskStateAnyOf3
   */
  detaching: string
}

export function DiskStateAnyOf3FromJSON(json: any): DiskStateAnyOf3 {
  return DiskStateAnyOf3FromJSONTyped(json, false)
}

export function DiskStateAnyOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DiskStateAnyOf3 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    detaching: json['detaching'],
  }
}

export function DiskStateAnyOf3ToJSON(value?: DiskStateAnyOf3 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    detaching: value.detaching,
  }
}
