/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Supported set of sort modes for scanning by id only.
 *
 * Currently, we only support scanning in ascending order.
 * @export
 * @enum {string}
 */
export enum IdSortMode {
  IdAscending = 'id-ascending',
}

export function IdSortModeFromJSON(json: any): IdSortMode {
  return IdSortModeFromJSONTyped(json, false)
}

export function IdSortModeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IdSortMode {
  return json as IdSortMode
}

export function IdSortModeToJSON(value?: IdSortMode | null): any {
  return value as any
}
