/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  Instance,
  InstanceFromJSON,
  InstanceFromJSONTyped,
  InstanceToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface InstanceResultsPage
 */
export interface InstanceResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<Instance>}
   * @memberof InstanceResultsPage
   */
  items: Array<Instance>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof InstanceResultsPage
   */
  nextPage?: string
}

export function InstanceResultsPageFromJSON(json: any): InstanceResultsPage {
  return InstanceResultsPageFromJSONTyped(json, false)
}

export function InstanceResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InstanceResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(InstanceFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function InstanceResultsPageToJSON(
  value?: InstanceResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(InstanceToJSON),
    next_page: value.nextPage,
  }
}
