/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Create-time parameters for an [`Instance`]
 * @export
 * @interface InstanceCreateParams
 */
export interface InstanceCreateParams {
  /**
   *
   * @type {string}
   * @memberof InstanceCreateParams
   */
  description: string
  /**
   *
   * @type {string}
   * @memberof InstanceCreateParams
   */
  hostname: string
  /**
   * A count of bytes, typically used either for memory or storage capacity
   *
   * The maximum supported byte count is [`i64::MAX`].  This makes it somewhat inconvenient to define constructors: a u32 constructor can be infallible, but an i64 constructor can fail (if the value is negative) and a u64 constructor can fail (if the value is larger than i64::MAX).  We provide all of these for consumers' convenience.
   * @type {number}
   * @memberof InstanceCreateParams
   */
  memory: number
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof InstanceCreateParams
   */
  name: string
  /**
   * The number of CPUs in an Instance
   * @type {number}
   * @memberof InstanceCreateParams
   */
  ncpus: number
}

export function InstanceCreateParamsFromJSON(json: any): InstanceCreateParams {
  return InstanceCreateParamsFromJSONTyped(json, false)
}

export function InstanceCreateParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InstanceCreateParams {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    hostname: json['hostname'],
    memory: json['memory'],
    name: json['name'],
    ncpus: json['ncpus'],
  }
}

export function InstanceCreateParamsToJSON(
  value?: InstanceCreateParams | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    hostname: value.hostname,
    memory: value.memory,
    name: value.name,
    ncpus: value.ncpus,
  }
}
