/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Supported set of sort modes for scanning by name only
 *
 * Currently, we only support scanning in ascending order.
 * @export
 * @enum {string}
 */
export enum NameSortMode {
  NameAscending = 'name-ascending',
}

export function NameSortModeFromJSON(json: any): NameSortMode {
  return NameSortModeFromJSONTyped(json, false)
}

export function NameSortModeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): NameSortMode {
  return json as NameSortMode
}

export function NameSortModeToJSON(value?: NameSortMode | null): any {
  return value as any
}
