/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Client view of an [`Organization`]
 * @export
 * @interface Organization
 */
export interface Organization {
  /**
   * human-readable free-form text about a resource
   * @type {string}
   * @memberof Organization
   */
  description: string
  /**
   * unique, immutable, system-controlled identifier for each resource
   * @type {string}
   * @memberof Organization
   */
  id: string
  /**
   * unique, mutable, user-controlled identifier for each resource
   * @type {string}
   * @memberof Organization
   */
  name: string
  /**
   * timestamp when this resource was created
   * @type {Date}
   * @memberof Organization
   */
  timeCreated: Date
  /**
   * timestamp when this resource was last modified
   * @type {Date}
   * @memberof Organization
   */
  timeModified: Date
}

export function OrganizationFromJSON(json: any): Organization {
  return OrganizationFromJSONTyped(json, false)
}

export function OrganizationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Organization {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    id: json['id'],
    name: json['name'],
    timeCreated: new Date(json['timeCreated']),
    timeModified: new Date(json['timeModified']),
  }
}

export function OrganizationToJSON(value?: Organization | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    id: value.id,
    name: value.name,
    timeCreated: value.timeCreated.toISOString(),
    timeModified: value.timeModified.toISOString(),
  }
}
