/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Create-time parameters for an [`Organization`]
 * @export
 * @interface OrganizationCreate
 */
export interface OrganizationCreate {
  /**
   *
   * @type {string}
   * @memberof OrganizationCreate
   */
  description: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof OrganizationCreate
   */
  name: string
}

export function OrganizationCreateFromJSON(json: any): OrganizationCreate {
  return OrganizationCreateFromJSONTyped(json, false)
}

export function OrganizationCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OrganizationCreate {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    name: json['name'],
  }
}

export function OrganizationCreateToJSON(
  value?: OrganizationCreate | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    name: value.name,
  }
}
