/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Updateable properties of an [`Organization`]
 * @export
 * @interface OrganizationUpdate
 */
export interface OrganizationUpdate {
  /**
   *
   * @type {string}
   * @memberof OrganizationUpdate
   */
  description?: string | null
  /**
   *
   * @type {string}
   * @memberof OrganizationUpdate
   */
  name?: string | null
}

export function OrganizationUpdateFromJSON(json: any): OrganizationUpdate {
  return OrganizationUpdateFromJSONTyped(json, false)
}

export function OrganizationUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OrganizationUpdate {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: !exists(json, 'description') ? undefined : json['description'],
    name: !exists(json, 'name') ? undefined : json['name'],
  }
}

export function OrganizationUpdateToJSON(
  value?: OrganizationUpdate | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    name: value.name,
  }
}
