/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Updateable properties of an [`Project`]
 * @export
 * @interface ProjectUpdateParams
 */
export interface ProjectUpdateParams {
  /**
   *
   * @type {string}
   * @memberof ProjectUpdateParams
   */
  description?: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof ProjectUpdateParams
   */
  name?: string
}

export function ProjectUpdateParamsFromJSON(json: any): ProjectUpdateParams {
  return ProjectUpdateParamsFromJSONTyped(json, false)
}

export function ProjectUpdateParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProjectUpdateParams {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: !exists(json, 'description') ? undefined : json['description'],
    name: !exists(json, 'name') ? undefined : json['name'],
  }
}

export function ProjectUpdateParamsToJSON(
  value?: ProjectUpdateParams | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    name: value.name,
  }
}
