/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  Project,
  ProjectFromJSON,
  ProjectFromJSONTyped,
  ProjectToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface ProjectResultsPage
 */
export interface ProjectResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<Project>}
   * @memberof ProjectResultsPage
   */
  items: Array<Project>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof ProjectResultsPage
   */
  nextPage?: string | null
}

export function ProjectResultsPageFromJSON(json: any): ProjectResultsPage {
  return ProjectResultsPageFromJSONTyped(json, false)
}

export function ProjectResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProjectResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(ProjectFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function ProjectResultsPageToJSON(
  value?: ProjectResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(ProjectToJSON),
    next_page: value.nextPage,
  }
}
