/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ProjectView,
  ProjectViewFromJSON,
  ProjectViewFromJSONTyped,
  ProjectViewToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface ProjectViewResultsPage
 */
export interface ProjectViewResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<ProjectView>}
   * @memberof ProjectViewResultsPage
   */
  items: Array<ProjectView>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof ProjectViewResultsPage
   */
  nextPage?: string
}

export function ProjectViewResultsPageFromJSON(
  json: any
): ProjectViewResultsPage {
  return ProjectViewResultsPageFromJSONTyped(json, false)
}

export function ProjectViewResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProjectViewResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(ProjectViewFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function ProjectViewResultsPageToJSON(
  value?: ProjectViewResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(ProjectViewToJSON),
    next_page: value.nextPage,
  }
}
