/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  RackView,
  RackViewFromJSON,
  RackViewFromJSONTyped,
  RackViewToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface RackViewResultsPage
 */
export interface RackViewResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<RackView>}
   * @memberof RackViewResultsPage
   */
  items: Array<RackView>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof RackViewResultsPage
   */
  nextPage?: string
}

export function RackViewResultsPageFromJSON(json: any): RackViewResultsPage {
  return RackViewResultsPageFromJSONTyped(json, false)
}

export function RackViewResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RackViewResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(RackViewFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function RackViewResultsPageToJSON(
  value?: RackViewResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(RackViewToJSON),
    next_page: value.nextPage,
  }
}
