/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApiProjectView,
  ApiProjectViewFromJSON,
  ApiProjectViewFromJSONTyped,
  ApiProjectViewToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface ResultsPageForApiProjectView
 */
export interface ResultsPageForApiProjectView {
  /**
   * list of items on this page of results
   * @type {Array<ApiProjectView>}
   * @memberof ResultsPageForApiProjectView
   */
  items: Array<ApiProjectView>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof ResultsPageForApiProjectView
   */
  nextPage?: string
}

export function ResultsPageForApiProjectViewFromJSON(
  json: any
): ResultsPageForApiProjectView {
  return ResultsPageForApiProjectViewFromJSONTyped(json, false)
}

export function ResultsPageForApiProjectViewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResultsPageForApiProjectView {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(ApiProjectViewFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function ResultsPageForApiProjectViewToJSON(
  value?: ResultsPageForApiProjectView | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(ApiProjectViewToJSON),
    next_page: value.nextPage,
  }
}
