/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  RouteDestinationOneOf,
  RouteDestinationOneOf1,
  RouteDestinationOneOf2,
  RouteDestinationOneOfFromJSONTyped,
  RouteDestinationOneOfToJSON,
  RouteDestinationOneOf1FromJSONTyped,
  RouteDestinationOneOf1ToJSON,
  RouteDestinationOneOf2FromJSONTyped,
  RouteDestinationOneOf2ToJSON,
} from './'

/**
 * @type RouteDestination
 * A subset of [`NetworkTarget`], `RouteDestination` specifies the kind of network traffic that will be matched to be forwarded to the [`RouteTarget`].
 * @export
 */
export type RouteDestination =
  | RouteDestinationOneOf
  | RouteDestinationOneOf1
  | RouteDestinationOneOf2

export function RouteDestinationFromJSON(json: any): RouteDestination {
  return RouteDestinationFromJSONTyped(json, false)
}

export function RouteDestinationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RouteDestination {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ...RouteDestinationOneOfFromJSONTyped(json, true),
    ...RouteDestinationOneOf1FromJSONTyped(json, true),
    ...RouteDestinationOneOf2FromJSONTyped(json, true),
  }
}

export function RouteDestinationToJSON(value?: RouteDestination | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ...RouteDestinationOneOfToJSON(value as any),
    ...RouteDestinationOneOf1ToJSON(value as any),
    ...RouteDestinationOneOf2ToJSON(value as any),
  }
}
