/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface RouteTargetOneOf
 */
export interface RouteTargetOneOf {
  /**
   *
   * @type {string}
   * @memberof RouteTargetOneOf
   */
  type: 'instance'
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof RouteTargetOneOf
   */
  value: string
}

export function RouteTargetOneOfFromJSON(json: any): RouteTargetOneOf {
  return RouteTargetOneOfFromJSONTyped(json, false)
}

export function RouteTargetOneOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RouteTargetOneOf {
  if (json === undefined || json === null) {
    return json
  }
  return {
    type: json['type'],
    value: json['value'],
  }
}

export function RouteTargetOneOfToJSON(value?: RouteTargetOneOf | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    type: value.type,
    value: value.value,
  }
}
