/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface RouteDestinationOneOf1
 */
export interface RouteDestinationOneOf1 {
  /**
   *
   * @type {string}
   * @memberof RouteDestinationOneOf1
   */
  type: 'vpc'
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof RouteDestinationOneOf1
   */
  value: string
}

export function RouteDestinationOneOf1FromJSON(
  json: any
): RouteDestinationOneOf1 {
  return RouteDestinationOneOf1FromJSONTyped(json, false)
}

export function RouteDestinationOneOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RouteDestinationOneOf1 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    type: json['type'],
    value: json['value'],
  }
}

export function RouteDestinationOneOf1ToJSON(
  value?: RouteDestinationOneOf1 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    type: value.type,
    value: value.value,
  }
}
