/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface RouteDestinationOneOf
 */
export interface RouteDestinationOneOf {
  /**
   *
   * @type {string}
   * @memberof RouteDestinationOneOf
   */
  type: 'ip'
  /**
   *
   * @type {string}
   * @memberof RouteDestinationOneOf
   */
  value: string
}

export function RouteDestinationOneOfFromJSON(
  json: any
): RouteDestinationOneOf {
  return RouteDestinationOneOfFromJSONTyped(json, false)
}

export function RouteDestinationOneOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RouteDestinationOneOf {
  if (json === undefined || json === null) {
    return json
  }
  return {
    type: json['type'],
    value: json['value'],
  }
}

export function RouteDestinationOneOfToJSON(
  value?: RouteDestinationOneOf | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    type: value.type,
    value: value.value,
  }
}
