/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  SagaStateOneOf,
  SagaStateOneOf1,
  SagaStateOneOf2,
  SagaStateOneOfFromJSONTyped,
  SagaStateOneOfToJSON,
  SagaStateOneOf1FromJSONTyped,
  SagaStateOneOf1ToJSON,
  SagaStateOneOf2FromJSONTyped,
  SagaStateOneOf2ToJSON,
} from './'

/**
 * @type SagaState
 *
 * @export
 */
export type SagaState = SagaStateOneOf | SagaStateOneOf1 | SagaStateOneOf2

export function SagaStateFromJSON(json: any): SagaState {
  return SagaStateFromJSONTyped(json, false)
}

export function SagaStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaState {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ...SagaStateOneOfFromJSONTyped(json, true),
    ...SagaStateOneOf1FromJSONTyped(json, true),
    ...SagaStateOneOf2FromJSONTyped(json, true),
  }
}

export function SagaStateToJSON(value?: SagaState | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ...SagaStateOneOfToJSON(value),
    ...SagaStateOneOf1ToJSON(value),
    ...SagaStateOneOf2ToJSON(value),
  }
}
