/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ActionError,
  ActionErrorFromJSON,
  ActionErrorFromJSONTyped,
  ActionErrorToJSON,
} from './'

/**
 *
 * @export
 * @interface SagaStateAnyOf1Done
 */
export interface SagaStateAnyOf1Done {
  /**
   *
   * @type {ActionError}
   * @memberof SagaStateAnyOf1Done
   */
  errorInfo?: ActionError
  /**
   *
   * @type {string}
   * @memberof SagaStateAnyOf1Done
   */
  errorNodeName?: string
  /**
   *
   * @type {boolean}
   * @memberof SagaStateAnyOf1Done
   */
  failed: boolean
}

export function SagaStateAnyOf1DoneFromJSON(json: any): SagaStateAnyOf1Done {
  return SagaStateAnyOf1DoneFromJSONTyped(json, false)
}

export function SagaStateAnyOf1DoneFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaStateAnyOf1Done {
  if (json === undefined || json === null) {
    return json
  }
  return {
    errorInfo: !exists(json, 'errorInfo')
      ? undefined
      : ActionErrorFromJSON(json['errorInfo']),
    errorNodeName: !exists(json, 'errorNodeName')
      ? undefined
      : json['errorNodeName'],
    failed: json['failed'],
  }
}

export function SagaStateAnyOf1DoneToJSON(
  value?: SagaStateAnyOf1Done | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    errorInfo: ActionErrorToJSON(value.errorInfo),
    errorNodeName: value.errorNodeName,
    failed: value.failed,
  }
}
