/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SagaErrorInfoOneOf3
 */
export interface SagaErrorInfoOneOf3 {
  /**
   *
   * @type {string}
   * @memberof SagaErrorInfoOneOf3
   */
  error: SagaErrorInfoOneOf3ErrorEnum
  /**
   *
   * @type {string}
   * @memberof SagaErrorInfoOneOf3
   */
  message: string
}

/**
 * @export
 * @enum {string}
 */
export enum SagaErrorInfoOneOf3ErrorEnum {
  SerializeFailed = 'serializeFailed',
}

export function SagaErrorInfoOneOf3FromJSON(json: any): SagaErrorInfoOneOf3 {
  return SagaErrorInfoOneOf3FromJSONTyped(json, false)
}

export function SagaErrorInfoOneOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaErrorInfoOneOf3 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    error: json['error'],
    message: json['message'],
  }
}

export function SagaErrorInfoOneOf3ToJSON(
  value?: SagaErrorInfoOneOf3 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    error: value.error,
    message: value.message,
  }
}
