/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SagaView,
  SagaViewFromJSON,
  SagaViewFromJSONTyped,
  SagaViewToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface SagaViewResultsPage
 */
export interface SagaViewResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<SagaView>}
   * @memberof SagaViewResultsPage
   */
  items: Array<SagaView>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof SagaViewResultsPage
   */
  nextPage?: string
}

export function SagaViewResultsPageFromJSON(json: any): SagaViewResultsPage {
  return SagaViewResultsPageFromJSONTyped(json, false)
}

export function SagaViewResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaViewResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(SagaViewFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function SagaViewResultsPageToJSON(
  value?: SagaViewResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(SagaViewToJSON),
    next_page: value.nextPage,
  }
}
