/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SagaErrorInfoOneOf2
 */
export interface SagaErrorInfoOneOf2 {
  /**
   *
   * @type {string}
   * @memberof SagaErrorInfoOneOf2
   */
  error: SagaErrorInfoOneOf2ErrorEnum
}

/**
 * @export
 * @enum {string}
 */
export enum SagaErrorInfoOneOf2ErrorEnum {
  InjectedError = 'injectedError',
}

export function SagaErrorInfoOneOf2FromJSON(json: any): SagaErrorInfoOneOf2 {
  return SagaErrorInfoOneOf2FromJSONTyped(json, false)
}

export function SagaErrorInfoOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaErrorInfoOneOf2 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    error: json['error'],
  }
}

export function SagaErrorInfoOneOf2ToJSON(
  value?: SagaErrorInfoOneOf2 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    error: value.error,
  }
}
