/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SagaState,
  SagaStateFromJSON,
  SagaStateFromJSONTyped,
  SagaStateToJSON,
} from './'

/**
 *
 * @export
 * @interface Saga
 */
export interface Saga {
  /**
   *
   * @type {string}
   * @memberof Saga
   */
  id: string
  /**
   *
   * @type {SagaState}
   * @memberof Saga
   */
  state: SagaState
}

export function SagaFromJSON(json: any): Saga {
  return SagaFromJSONTyped(json, false)
}

export function SagaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Saga {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    state: SagaStateFromJSON(json['state']),
  }
}

export function SagaToJSON(value?: Saga | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    state: SagaStateToJSON(value.state),
  }
}
