/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SagaStateAnyOf,
  SagaStateAnyOfFromJSON,
  SagaStateAnyOfFromJSONTyped,
  SagaStateAnyOfToJSON,
  SagaStateAnyOf1,
  SagaStateAnyOf1FromJSON,
  SagaStateAnyOf1FromJSONTyped,
  SagaStateAnyOf1ToJSON,
  SagaStateAnyOf1Done,
  SagaStateAnyOf1DoneFromJSON,
  SagaStateAnyOf1DoneFromJSONTyped,
  SagaStateAnyOf1DoneToJSON,
} from './'

/**
 *
 * @export
 * @interface SagaState
 */
export interface SagaState {
  /**
   *
   * @type {SagaStateAnyOf1Done}
   * @memberof SagaState
   */
  done: SagaStateAnyOf1Done
}

export function SagaStateFromJSON(json: any): SagaState {
  return SagaStateFromJSONTyped(json, false)
}

export function SagaStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaState {
  if (json === undefined || json === null) {
    return json
  }
  return {
    done: SagaStateAnyOf1DoneFromJSON(json['done']),
  }
}

export function SagaStateToJSON(value?: SagaState | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    done: SagaStateAnyOf1DoneToJSON(value.done),
  }
}
