/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SagaStateAnyOf1Done,
  SagaStateAnyOf1DoneFromJSON,
  SagaStateAnyOf1DoneFromJSONTyped,
  SagaStateAnyOf1DoneToJSON,
} from './'

/**
 *
 * @export
 * @interface SagaStateAnyOf1
 */
export interface SagaStateAnyOf1 {
  /**
   *
   * @type {SagaStateAnyOf1Done}
   * @memberof SagaStateAnyOf1
   */
  done: SagaStateAnyOf1Done
}

export function SagaStateAnyOf1FromJSON(json: any): SagaStateAnyOf1 {
  return SagaStateAnyOf1FromJSONTyped(json, false)
}

export function SagaStateAnyOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaStateAnyOf1 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    done: SagaStateAnyOf1DoneFromJSON(json['done']),
  }
}

export function SagaStateAnyOf1ToJSON(value?: SagaStateAnyOf1 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    done: SagaStateAnyOf1DoneToJSON(value.done),
  }
}
