/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SagaErrorInfo,
  SagaErrorInfoFromJSON,
  SagaErrorInfoFromJSONTyped,
  SagaErrorInfoToJSON,
} from './'

/**
 *
 * @export
 * @interface SagaStateOneOf2
 */
export interface SagaStateOneOf2 {
  /**
   *
   * @type {SagaErrorInfo}
   * @memberof SagaStateOneOf2
   */
  errorInfo: SagaErrorInfo
  /**
   *
   * @type {string}
   * @memberof SagaStateOneOf2
   */
  errorNodeName: string
  /**
   *
   * @type {string}
   * @memberof SagaStateOneOf2
   */
  state: 'failed'
}

export function SagaStateOneOf2FromJSON(json: any): SagaStateOneOf2 {
  return SagaStateOneOf2FromJSONTyped(json, false)
}

export function SagaStateOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaStateOneOf2 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    errorInfo: SagaErrorInfoFromJSON(json['error_info']),
    errorNodeName: json['error_node_name'],
    state: json['state'],
  }
}

export function SagaStateOneOf2ToJSON(value?: SagaStateOneOf2 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    error_info: SagaErrorInfoToJSON(value.errorInfo),
    error_node_name: value.errorNodeName,
    state: value.state,
  }
}
