/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SagaStateOneOf1
 */
export interface SagaStateOneOf1 {
  /**
   *
   * @type {string}
   * @memberof SagaStateOneOf1
   */
  state: 'succeeded'
}

export function SagaStateOneOf1FromJSON(json: any): SagaStateOneOf1 {
  return SagaStateOneOf1FromJSONTyped(json, false)
}

export function SagaStateOneOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaStateOneOf1 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    state: json['state'],
  }
}

export function SagaStateOneOf1ToJSON(value?: SagaStateOneOf1 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    state: value.state,
  }
}
