/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum SagaStateAnyOf {
  Running = 'running',
}

export function SagaStateAnyOfFromJSON(json: any): SagaStateAnyOf {
  return SagaStateAnyOfFromJSONTyped(json, false)
}

export function SagaStateAnyOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaStateAnyOf {
  return json as SagaStateAnyOf
}

export function SagaStateAnyOfToJSON(value?: SagaStateAnyOf | null): any {
  return value as any
}
