/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ActionError,
  ActionErrorFromJSON,
  ActionErrorFromJSONTyped,
  ActionErrorToJSON,
} from './'

/**
 *
 * @export
 * @interface SagaStateViewAnyOf1Done
 */
export interface SagaStateViewAnyOf1Done {
  /**
   *
   * @type {ActionError}
   * @memberof SagaStateViewAnyOf1Done
   */
  errorInfo?: ActionError
  /**
   *
   * @type {string}
   * @memberof SagaStateViewAnyOf1Done
   */
  errorNodeName?: string
  /**
   *
   * @type {boolean}
   * @memberof SagaStateViewAnyOf1Done
   */
  failed: boolean
}

export function SagaStateViewAnyOf1DoneFromJSON(
  json: any
): SagaStateViewAnyOf1Done {
  return SagaStateViewAnyOf1DoneFromJSONTyped(json, false)
}

export function SagaStateViewAnyOf1DoneFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaStateViewAnyOf1Done {
  if (json === undefined || json === null) {
    return json
  }
  return {
    errorInfo: !exists(json, 'errorInfo')
      ? undefined
      : ActionErrorFromJSON(json['errorInfo']),
    errorNodeName: !exists(json, 'errorNodeName')
      ? undefined
      : json['errorNodeName'],
    failed: json['failed'],
  }
}

export function SagaStateViewAnyOf1DoneToJSON(
  value?: SagaStateViewAnyOf1Done | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    errorInfo: ActionErrorToJSON(value.errorInfo),
    errorNodeName: value.errorNodeName,
    failed: value.failed,
  }
}
