/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SagaErrorInfoAnyOf3
 */
export interface SagaErrorInfoAnyOf3 {
  /**
   *
   * @type {string}
   * @memberof SagaErrorInfoAnyOf3
   */
  error: SagaErrorInfoAnyOf3ErrorEnum
  /**
   *
   * @type {string}
   * @memberof SagaErrorInfoAnyOf3
   */
  message: string
}

/**
 * @export
 * @enum {string}
 */
export enum SagaErrorInfoAnyOf3ErrorEnum {
  SerializeFailed = 'serializeFailed',
}

export function SagaErrorInfoAnyOf3FromJSON(json: any): SagaErrorInfoAnyOf3 {
  return SagaErrorInfoAnyOf3FromJSONTyped(json, false)
}

export function SagaErrorInfoAnyOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaErrorInfoAnyOf3 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    error: json['error'],
    message: json['message'],
  }
}

export function SagaErrorInfoAnyOf3ToJSON(
  value?: SagaErrorInfoAnyOf3 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    error: value.error,
    message: value.message,
  }
}
