/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SagaErrorInfoOneOf
 */
export interface SagaErrorInfoOneOf {
  /**
   *
   * @type {string}
   * @memberof SagaErrorInfoOneOf
   */
  error: SagaErrorInfoOneOfErrorEnum
  /**
   *
   * @type {any}
   * @memberof SagaErrorInfoOneOf
   */
  sourceError: any | null
}

/**
 * @export
 * @enum {string}
 */
export enum SagaErrorInfoOneOfErrorEnum {
  ActionFailed = 'actionFailed',
}

export function SagaErrorInfoOneOfFromJSON(json: any): SagaErrorInfoOneOf {
  return SagaErrorInfoOneOfFromJSONTyped(json, false)
}

export function SagaErrorInfoOneOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaErrorInfoOneOf {
  if (json === undefined || json === null) {
    return json
  }
  return {
    error: json['error'],
    sourceError: json['source_error'],
  }
}

export function SagaErrorInfoOneOfToJSON(
  value?: SagaErrorInfoOneOf | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    error: value.error,
    source_error: value.sourceError,
  }
}
