/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SagaErrorInfoAnyOf4
 */
export interface SagaErrorInfoAnyOf4 {
  /**
   *
   * @type {string}
   * @memberof SagaErrorInfoAnyOf4
   */
  error: SagaErrorInfoAnyOf4ErrorEnum
  /**
   *
   * @type {string}
   * @memberof SagaErrorInfoAnyOf4
   */
  message: string
}

/**
 * @export
 * @enum {string}
 */
export enum SagaErrorInfoAnyOf4ErrorEnum {
  SubsagaCreateFailed = 'subsagaCreateFailed',
}

export function SagaErrorInfoAnyOf4FromJSON(json: any): SagaErrorInfoAnyOf4 {
  return SagaErrorInfoAnyOf4FromJSONTyped(json, false)
}

export function SagaErrorInfoAnyOf4FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaErrorInfoAnyOf4 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    error: json['error'],
    message: json['message'],
  }
}

export function SagaErrorInfoAnyOf4ToJSON(
  value?: SagaErrorInfoAnyOf4 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    error: value.error,
    message: value.message,
  }
}
