/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SagaErrorInfo,
  SagaErrorInfoFromJSON,
  SagaErrorInfoFromJSONTyped,
  SagaErrorInfoToJSON,
} from './'

/**
 *
 * @export
 * @interface SagaStateAnyOf2
 */
export interface SagaStateAnyOf2 {
  /**
   *
   * @type {SagaErrorInfo}
   * @memberof SagaStateAnyOf2
   */
  errorInfo: SagaErrorInfo
  /**
   *
   * @type {string}
   * @memberof SagaStateAnyOf2
   */
  errorNodeName: string
  /**
   *
   * @type {string}
   * @memberof SagaStateAnyOf2
   */
  state: SagaStateAnyOf2StateEnum
}

/**
 * @export
 * @enum {string}
 */
export enum SagaStateAnyOf2StateEnum {
  Failed = 'failed',
}

export function SagaStateAnyOf2FromJSON(json: any): SagaStateAnyOf2 {
  return SagaStateAnyOf2FromJSONTyped(json, false)
}

export function SagaStateAnyOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SagaStateAnyOf2 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    errorInfo: SagaErrorInfoFromJSON(json['error_info']),
    errorNodeName: json['error_node_name'],
    state: json['state'],
  }
}

export function SagaStateAnyOf2ToJSON(value?: SagaStateAnyOf2 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    error_info: SagaErrorInfoToJSON(value.errorInfo),
    error_node_name: value.errorNodeName,
    state: value.state,
  }
}
