/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SledView,
  SledViewFromJSON,
  SledViewFromJSONTyped,
  SledViewToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface SledViewResultsPage
 */
export interface SledViewResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<SledView>}
   * @memberof SledViewResultsPage
   */
  items: Array<SledView>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof SledViewResultsPage
   */
  nextPage?: string
}

export function SledViewResultsPageFromJSON(json: any): SledViewResultsPage {
  return SledViewResultsPageFromJSONTyped(json, false)
}

export function SledViewResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SledViewResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(SledViewFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function SledViewResultsPageToJSON(
  value?: SledViewResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(SledViewToJSON),
    next_page: value.nextPage,
  }
}
