/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { Sled, SledFromJSON, SledFromJSONTyped, SledToJSON } from './'

/**
 * A single page of results
 * @export
 * @interface SledResultsPage
 */
export interface SledResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<Sled>}
   * @memberof SledResultsPage
   */
  items: Array<Sled>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof SledResultsPage
   */
  nextPage?: string | null
}

export function SledResultsPageFromJSON(json: any): SledResultsPage {
  return SledResultsPageFromJSONTyped(json, false)
}

export function SledResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SledResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(SledFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function SledResultsPageToJSON(value?: SledResultsPage | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(SledToJSON),
    next_page: value.nextPage,
  }
}
