/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Identity-related metadata that's included in nearly all public API objects
 * @export
 * @interface Vpc
 */
export interface Vpc {
  /**
   * human-readable free-form text about a resource
   * @type {string}
   * @memberof Vpc
   */
  description: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof Vpc
   */
  dnsName: string
  /**
   * unique, immutable, system-controlled identifier for each resource
   * @type {string}
   * @memberof Vpc
   */
  id: string
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof Vpc
   */
  name: string
  /**
   * id for the project containing this VPC
   * @type {string}
   * @memberof Vpc
   */
  projectId: string
  /**
   * timestamp when this resource was created
   * @type {Date}
   * @memberof Vpc
   */
  timeCreated: Date
  /**
   * timestamp when this resource was last modified
   * @type {Date}
   * @memberof Vpc
   */
  timeModified: Date
}

export function VpcFromJSON(json: any): Vpc {
  return VpcFromJSONTyped(json, false)
}

export function VpcFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vpc {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    dnsName: json['dnsName'],
    id: json['id'],
    name: json['name'],
    projectId: json['projectId'],
    timeCreated: new Date(json['timeCreated']),
    timeModified: new Date(json['timeModified']),
  }
}

export function VpcToJSON(value?: Vpc | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    dnsName: value.dnsName,
    id: value.id,
    name: value.name,
    projectId: value.projectId,
    timeCreated: value.timeCreated.toISOString(),
    timeModified: value.timeModified.toISOString(),
  }
}
