/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum VpcFirewallRuleStatus {
  Disabled = 'disabled',
  Enabled = 'enabled',
}

export function VpcFirewallRuleStatusFromJSON(
  json: any
): VpcFirewallRuleStatus {
  return VpcFirewallRuleStatusFromJSONTyped(json, false)
}

export function VpcFirewallRuleStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcFirewallRuleStatus {
  return json as VpcFirewallRuleStatus
}

export function VpcFirewallRuleStatusToJSON(
  value?: VpcFirewallRuleStatus | null
): any {
  return value as any
}
