/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum VpcFirewallRuleAction {
  Allow = 'allow',
  Deny = 'deny',
}

export function VpcFirewallRuleActionFromJSON(
  json: any
): VpcFirewallRuleAction {
  return VpcFirewallRuleActionFromJSONTyped(json, false)
}

export function VpcFirewallRuleActionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcFirewallRuleAction {
  return json as VpcFirewallRuleAction
}

export function VpcFirewallRuleActionToJSON(
  value?: VpcFirewallRuleAction | null
): any {
  return value as any
}
