/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The protocols that may be specified in a firewall rule's filter
 * @export
 * @enum {string}
 */
export enum VpcFirewallRuleProtocol {
  Tcp = 'TCP',
  Udp = 'UDP',
  Icmp = 'ICMP',
}

export function VpcFirewallRuleProtocolFromJSON(
  json: any
): VpcFirewallRuleProtocol {
  return VpcFirewallRuleProtocolFromJSONTyped(json, false)
}

export function VpcFirewallRuleProtocolFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcFirewallRuleProtocol {
  return json as VpcFirewallRuleProtocol
}

export function VpcFirewallRuleProtocolToJSON(
  value?: VpcFirewallRuleProtocol | null
): any {
  return value as any
}
