/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  VpcFirewallRuleAction,
  VpcFirewallRuleActionFromJSON,
  VpcFirewallRuleActionFromJSONTyped,
  VpcFirewallRuleActionToJSON,
  VpcFirewallRuleDirection,
  VpcFirewallRuleDirectionFromJSON,
  VpcFirewallRuleDirectionFromJSONTyped,
  VpcFirewallRuleDirectionToJSON,
  VpcFirewallRuleFilter,
  VpcFirewallRuleFilterFromJSON,
  VpcFirewallRuleFilterFromJSONTyped,
  VpcFirewallRuleFilterToJSON,
  VpcFirewallRuleStatus,
  VpcFirewallRuleStatusFromJSON,
  VpcFirewallRuleStatusFromJSONTyped,
  VpcFirewallRuleStatusToJSON,
  VpcFirewallRuleTarget,
  VpcFirewallRuleTargetFromJSON,
  VpcFirewallRuleTargetFromJSONTyped,
  VpcFirewallRuleTargetToJSON,
} from './'

/**
 * A single rule in a VPC firewall
 * @export
 * @interface VpcFirewallRuleUpdate
 */
export interface VpcFirewallRuleUpdate {
  /**
   * whether traffic matching the rule should be allowed or dropped
   * @type {VpcFirewallRuleAction}
   * @memberof VpcFirewallRuleUpdate
   */
  action: VpcFirewallRuleAction
  /**
   * human-readable free-form text about a resource
   * @type {string}
   * @memberof VpcFirewallRuleUpdate
   */
  description: string
  /**
   * whether this rule is for incoming or outgoing traffic
   * @type {VpcFirewallRuleDirection}
   * @memberof VpcFirewallRuleUpdate
   */
  direction: VpcFirewallRuleDirection
  /**
   * reductions on the scope of the rule
   * @type {VpcFirewallRuleFilter}
   * @memberof VpcFirewallRuleUpdate
   */
  filters: VpcFirewallRuleFilter
  /**
   * the relative priority of this rule
   * @type {number}
   * @memberof VpcFirewallRuleUpdate
   */
  priority: number
  /**
   * whether this rule is in effect
   * @type {VpcFirewallRuleStatus}
   * @memberof VpcFirewallRuleUpdate
   */
  status: VpcFirewallRuleStatus
  /**
   * list of sets of instances that the rule applies to
   * @type {Array<VpcFirewallRuleTarget>}
   * @memberof VpcFirewallRuleUpdate
   */
  targets: Array<VpcFirewallRuleTarget>
}

export function VpcFirewallRuleUpdateFromJSON(
  json: any
): VpcFirewallRuleUpdate {
  return VpcFirewallRuleUpdateFromJSONTyped(json, false)
}

export function VpcFirewallRuleUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcFirewallRuleUpdate {
  if (json === undefined || json === null) {
    return json
  }
  return {
    action: VpcFirewallRuleActionFromJSON(json['action']),
    description: json['description'],
    direction: VpcFirewallRuleDirectionFromJSON(json['direction']),
    filters: VpcFirewallRuleFilterFromJSON(json['filters']),
    priority: json['priority'],
    status: VpcFirewallRuleStatusFromJSON(json['status']),
    targets: (json['targets'] as Array<any>).map(VpcFirewallRuleTargetFromJSON),
  }
}

export function VpcFirewallRuleUpdateToJSON(
  value?: VpcFirewallRuleUpdate | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    action: VpcFirewallRuleActionToJSON(value.action),
    description: value.description,
    direction: VpcFirewallRuleDirectionToJSON(value.direction),
    filters: VpcFirewallRuleFilterToJSON(value.filters),
    priority: value.priority,
    status: VpcFirewallRuleStatusToJSON(value.status),
    targets: (value.targets as Array<any>).map(VpcFirewallRuleTargetToJSON),
  }
}
