/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum VpcFirewallRuleDirection {
  Inbound = 'inbound',
  Outbound = 'outbound',
}

export function VpcFirewallRuleDirectionFromJSON(
  json: any
): VpcFirewallRuleDirection {
  return VpcFirewallRuleDirectionFromJSONTyped(json, false)
}

export function VpcFirewallRuleDirectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcFirewallRuleDirection {
  return json as VpcFirewallRuleDirection
}

export function VpcFirewallRuleDirectionToJSON(
  value?: VpcFirewallRuleDirection | null
): any {
  return value as any
}
