/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum VpcRouterKind {
  System = 'system',
  Custom = 'custom',
}

export function VpcRouterKindFromJSON(json: any): VpcRouterKind {
  return VpcRouterKindFromJSONTyped(json, false)
}

export function VpcRouterKindFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcRouterKind {
  return json as VpcRouterKind
}

export function VpcRouterKindToJSON(value?: VpcRouterKind | null): any {
  return value as any
}
