/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  IdentityMetadata,
  IdentityMetadataFromJSON,
  IdentityMetadataFromJSONTyped,
  IdentityMetadataToJSON,
} from './'

/**
 * A VPC router defines a series of rules that indicate where traffic should be sent depending on its destination.
 * @export
 * @interface VpcRouter
 */
export interface VpcRouter {
  /**
   * common identifying metadata
   * @type {IdentityMetadata}
   * @memberof VpcRouter
   */
  identity: IdentityMetadata
  /**
   * The VPC to which the router belongs.
   * @type {string}
   * @memberof VpcRouter
   */
  vpcId: string
}

export function VpcRouterFromJSON(json: any): VpcRouter {
  return VpcRouterFromJSONTyped(json, false)
}

export function VpcRouterFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcRouter {
  if (json === undefined || json === null) {
    return json
  }
  return {
    identity: IdentityMetadataFromJSON(json['identity']),
    vpcId: json['vpc_id'],
  }
}

export function VpcRouterToJSON(value?: VpcRouter | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    identity: IdentityMetadataToJSON(value.identity),
    vpc_id: value.vpcId,
  }
}
