/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  VpcRouter,
  VpcRouterFromJSON,
  VpcRouterFromJSONTyped,
  VpcRouterToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface VpcRouterResultsPage
 */
export interface VpcRouterResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<VpcRouter>}
   * @memberof VpcRouterResultsPage
   */
  items: Array<VpcRouter>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof VpcRouterResultsPage
   */
  nextPage?: string | null
}

export function VpcRouterResultsPageFromJSON(json: any): VpcRouterResultsPage {
  return VpcRouterResultsPageFromJSONTyped(json, false)
}

export function VpcRouterResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcRouterResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(VpcRouterFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function VpcRouterResultsPageToJSON(
  value?: VpcRouterResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(VpcRouterToJSON),
    next_page: value.nextPage,
  }
}
