/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  VpcSubnet,
  VpcSubnetFromJSON,
  VpcSubnetFromJSONTyped,
  VpcSubnetToJSON,
} from './'

/**
 * A single page of results
 * @export
 * @interface VpcSubnetResultsPage
 */
export interface VpcSubnetResultsPage {
  /**
   * list of items on this page of results
   * @type {Array<VpcSubnet>}
   * @memberof VpcSubnetResultsPage
   */
  items: Array<VpcSubnet>
  /**
   * token used to fetch the next page of results (if any)
   * @type {string}
   * @memberof VpcSubnetResultsPage
   */
  nextPage?: string
}

export function VpcSubnetResultsPageFromJSON(json: any): VpcSubnetResultsPage {
  return VpcSubnetResultsPageFromJSONTyped(json, false)
}

export function VpcSubnetResultsPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcSubnetResultsPage {
  if (json === undefined || json === null) {
    return json
  }
  return {
    items: (json['items'] as Array<any>).map(VpcSubnetFromJSON),
    nextPage: !exists(json, 'next_page') ? undefined : json['next_page'],
  }
}

export function VpcSubnetResultsPageToJSON(
  value?: VpcSubnetResultsPage | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    items: (value.items as Array<any>).map(VpcSubnetToJSON),
    next_page: value.nextPage,
  }
}
