/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Create-time parameters for a [`VpcSubnet`]
 * @export
 * @interface VpcSubnetCreate
 */
export interface VpcSubnetCreate {
  /**
   *
   * @type {string}
   * @memberof VpcSubnetCreate
   */
  description: string
  /**
   *
   * @type {string}
   * @memberof VpcSubnetCreate
   */
  ipv4Block?: string | null
  /**
   *
   * @type {string}
   * @memberof VpcSubnetCreate
   */
  ipv6Block?: string | null
  /**
   * Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'.
   * @type {string}
   * @memberof VpcSubnetCreate
   */
  name: string
}

export function VpcSubnetCreateFromJSON(json: any): VpcSubnetCreate {
  return VpcSubnetCreateFromJSONTyped(json, false)
}

export function VpcSubnetCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcSubnetCreate {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: json['description'],
    ipv4Block: !exists(json, 'ipv4Block') ? undefined : json['ipv4Block'],
    ipv6Block: !exists(json, 'ipv6Block') ? undefined : json['ipv6Block'],
    name: json['name'],
  }
}

export function VpcSubnetCreateToJSON(value?: VpcSubnetCreate | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    ipv4Block: value.ipv4Block,
    ipv6Block: value.ipv6Block,
    name: value.name,
  }
}
