/* tslint:disable */
/* eslint-disable */
/**
 * Oxide Region API
 * API for interacting with the Oxide control plane
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@oxide.computer
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Updateable properties of a [`Vpc`]
 * @export
 * @interface VpcUpdate
 */
export interface VpcUpdate {
  /**
   *
   * @type {string}
   * @memberof VpcUpdate
   */
  description?: string | null
  /**
   *
   * @type {string}
   * @memberof VpcUpdate
   */
  dnsName?: string | null
  /**
   *
   * @type {string}
   * @memberof VpcUpdate
   */
  name?: string | null
}

export function VpcUpdateFromJSON(json: any): VpcUpdate {
  return VpcUpdateFromJSONTyped(json, false)
}

export function VpcUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VpcUpdate {
  if (json === undefined || json === null) {
    return json
  }
  return {
    description: !exists(json, 'description') ? undefined : json['description'],
    dnsName: !exists(json, 'dnsName') ? undefined : json['dnsName'],
    name: !exists(json, 'name') ? undefined : json['name'],
  }
}

export function VpcUpdateToJSON(value?: VpcUpdate | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    description: value.description,
    dnsName: value.dnsName,
    name: value.name,
  }
}
