/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

/**
 * Generates a TypeScript module with per-character width ratios for our
 * sans (SuisseIntl) and mono (GT America Mono) fonts. Widths are stored as
 * a fraction of em-size so callers can multiply by font-size to get pixel
 * widths — no Canvas or DOM needed at runtime.
 *
 * Usage: npx tsx tools/gen-font-widths.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import opentype from 'opentype.js'

const FONTS_DIR = resolve(import.meta.dirname, '../app/ui/assets/fonts')
const OUT_PATH = resolve(import.meta.dirname, '../app/ui/lib/font-widths.gen.ts')

// Printable ASCII range
const FIRST_CHAR = 32 // space
const LAST_CHAR = 126 // tilde

function measureFont(fontPath: string): {
  widths: Record<string, number>
  defaultWidth: number
} {
  const buffer = readFileSync(fontPath)
  const font = opentype.parse(buffer.buffer)

  const widths: Record<string, number> = {}
  let totalWidth = 0
  let count = 0

  for (let code = FIRST_CHAR; code <= LAST_CHAR; code++) {
    const char = String.fromCharCode(code)
    const glyph = font.charToGlyph(char)
    if (glyph && glyph.advanceWidth != null) {
      const ratio = glyph.advanceWidth / font.unitsPerEm
      widths[char] = ratio
      totalWidth += ratio
      count++
    }
  }

  // Default width for unmapped characters — use the average
  const defaultWidth = count > 0 ? totalWidth / count : 0.5

  return { widths, defaultWidth }
}

function formatNumber(n: number): string {
  // 4 decimal places is plenty for proportional sizing
  return n.toFixed(4).replace(/0+$/, '').replace(/\.$/, '.0')
}

function escapeKey(char: string): string {
  if (char === "'") return '"\'"'
  if (char === '\\') return "'\\\\'"
  return `'${char}'`
}

const sans = measureFont(resolve(FONTS_DIR, 'SuisseIntl-Regular-WebS.woff'))
const mono = measureFont(resolve(FONTS_DIR, 'GT-America-Mono-Regular-OCC.woff'))

// For mono, verify all widths are the same (that's what makes it mono)
const monoVals = Object.values(mono.widths)
const monoWidth = monoVals[0]

let output = `/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

// Generated by tools/gen-font-widths.ts — do not edit

/** Per-character width as a fraction of font-size for SuisseIntl Regular */
export const sansWidths: Record<string, number> = {\n`

for (let code = FIRST_CHAR; code <= LAST_CHAR; code++) {
  const char = String.fromCharCode(code)
  const w = sans.widths[char]
  if (w != null) {
    output += `  ${escapeKey(char)}: ${formatNumber(w)},\n`
  }
}

output += `}

/** Fallback width for unmapped characters (average of all measured widths) */
export const sansDefaultWidth = ${formatNumber(sans.defaultWidth)}

/** GT America Mono Regular — single width for all characters */
export const monoWidth = ${formatNumber(monoWidth)}
`

writeFileSync(OUT_PATH, output)
console.info(`Generated ${OUT_PATH}`)
