/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

/**
 * Snapshot timeseries descriptions and units from the oximeter schema TOML
 * files at the pinned omicron commit. The schema list endpoint can't give us
 * these because the ClickHouse schema table doesn't store them, so Nexus
 * returns empty descriptions and `none` units for everything.
 *
 * Output is stamped with the omicron commit, and we skip fetching when the
 * stamp already matches OMICRON_VERSION. Pass --force to regenerate anyway.
 *
 * Usage: node tools/generate_timeseries_metadata.ts [--force]
 */
import fs from 'node:fs'
import path from 'node:path'

import * as R from 'remeda'
import { parse } from 'smol-toml'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT_FILE = path.join(ROOT, 'app/api/__generated__/timeseries-metadata.ts')
const SCHEMA_DIR = 'oximeter/oximeter/schema'

const sha = fs.readFileSync(path.join(ROOT, 'OMICRON_VERSION'), 'utf8').trim()

const existing = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, 'utf8') : ''
const existingSha = existing.match(/^export const omicronVersion = '(\w+)'$/m)?.[1]
if (existingSha === sha && !process.argv.includes('--force')) {
  console.info(`timeseries metadata already generated for ${sha}, skipping`)
  process.exit(0)
}

// fields are listed per version; we only care about the latest
type Versioned = { versions: { fields: string[] }[] }

type SchemaToml = {
  target: Versioned & { name: string; description: string }
  metrics: (Versioned & {
    name: string
    description: string
    units: string
    datum_type: string
  })[]
  fields: Record<string, { type: string; description: string }>
}

async function fetchOk(url: string, headers?: Record<string, string>) {
  const response = await fetch(url, { headers })
  if (!response.ok) throw new Error(`${response.status} fetching ${url}`)
  return response
}

// a token is optional, but avoids the low unauthenticated rate limit
const ghHeaders: Record<string, string> = process.env.GITHUB_TOKEN
  ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
  : {}

const listing: { name: string; download_url: string }[] = await fetchOk(
  `https://api.github.com/repos/oxidecomputer/omicron/contents/${SCHEMA_DIR}?ref=${sha}`,
  ghHeaders
).then((r) => r.json())

const tomlFiles = listing.filter((f) => f.name.endsWith('.toml'))
const schemas = await Promise.all(
  tomlFiles.map(async (f) => {
    const text = await fetchOk(f.download_url).then((r) => r.text())
    return {
      file: path.basename(f.name, '.toml'),
      ...(parse(text) as unknown as SchemaToml),
    }
  })
)

const latestFields = (fields: SchemaToml['fields'], { versions }: Versioned) =>
  versions[versions.length - 1].fields.map((name) => ({
    name,
    fieldType: fields[name].type,
    description: fields[name].description,
  }))

// Target fields are shared by every metric on the target, so they're stored
// once per target instead of being repeated on each timeseries. Targets are
// keyed by schema file because two files can define different targets with
// the same name (e.g., virtual_machine).
const targets = R.pipe(
  schemas,
  R.sortBy((s) => s.file),
  R.mapToObj(({ file, target, fields }) => [
    file,
    { description: target.description, fields: latestFields(fields, target) },
  ])
)

const timeseries = R.pipe(
  schemas,
  R.flatMap(({ file, target, metrics, fields }) =>
    metrics.map((metric) => ({
      name: `${target.name}:${metric.name}`,
      target: file,
      description: metric.description,
      units: metric.units,
      datumType: metric.datum_type,
      fields: latestFields(fields, metric),
    }))
  ),
  R.sortBy((t) => t.name),
  R.mapToObj(({ name, ...rest }) => [name, rest])
)

fs.writeFileSync(
  OUT_FILE,
  `/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

// generated by tools/generate_timeseries_metadata.ts from the oximeter schema
// TOML files in omicron. do not update manually. see docs/update-pinned-api.md

import type { DatumType, FieldSchema, Units } from './Api'

export const omicronVersion = '${sha}'

type Field = Omit<FieldSchema, 'source'>

export const targets: Partial<Record<string, { description: string; fields: Field[] }>> =
  ${JSON.stringify(targets)}

export const timeseries: Partial<
  Record<
    string,
    {
      /** key into \`targets\` */
      target: string
      description: string
      units: Units
      datumType: DatumType
      fields: Field[]
    }
  >
> = ${JSON.stringify(timeseries)}
`
)

console.info(
  `wrote ${Object.keys(timeseries).length} timeseries from ${tomlFiles.length} files to ${path.relative(ROOT, OUT_FILE)}`
)
