import type { Disk } from '@oxide/api'
import { GiB } from '@oxide/util'

import { instance } from './instance'
import type { Json } from './json-type'
import { genId } from './msw/util'
import { project } from './project'

export const disks: Json<Disk>[] = [
  {
    id: <uuid>,
    name: 'disk-1',
    description: "it's a disk",
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'attached', instance: instance.id },
    device_path: '/abc',
    size: 2 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-2',
    description: "it's a second disk",
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'attached', instance: instance.id },
    device_path: '/def',
    size: 4 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-3',
    description: "it's a third disk",
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/ghi',
    size: 6 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-4',
    description: "it's a fourth disk",
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/jkl',
    size: 64 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-5',
    description: '',
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/jkl',
    size: 128 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-6',
    description: '',
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/jkl',
    size: 20 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-7',
    description: '',
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/jkl',
    size: 24 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-8',
    description: '',
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/jkl',
    size: 16 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-9',
    description: '',
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/jkl',
    size: 32 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-10',
    description: '',
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/jkl',
    size: 24 * GiB,
    block_size: 2048,
  },
  {
    id: <uuid>,
    name: 'disk-11',
    description: '',
    project_id: project.id,
    time_created: new Date().toISOString(),
    time_modified: new Date().toISOString(),
    state: { state: 'detached' },
    device_path: '/jkl',
    size: 12 * GiB,
    block_size: 2048,
  },
]
