name: Deploy API

on:
  push:
    branches:
      - "main"

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
      - name: Install Google Cloud Docker
        run: gcloud components install docker-credential-gcr
      - name: Setup Docker for GCR
        run: gcloud auth configure-docker
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./ci/omicron/Dockerfile
          tags: gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/omicron-console-dev:main
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  preview:
    runs-on: ubuntu-latest
    needs: [container]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
      - name: Get HEAD Commit Hash
        id: commit
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      - name: Deploy Revision On Cloud Run
        run: |
          gcloud run deploy omicron-console-dev \
          --image "gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/omicron-console-dev:main" \
          --region "us-central1" \
          --platform=managed \
          --revision-suffix=main-${{steps.commit.outputs.hash}} \
          --allow-unauthenticated \
          --max-instances=1
      - name: Update Traffic
        run: |
          gcloud components install beta
          gcloud beta run services update-traffic omicron-console-dev \
            --update-tags main=omicron-console-dev-main-${{steps.commit.outputs.hash}} \
            --platform=managed \
            --region "us-central1" \
      - name: Get Preview URL
        id: preview-url
        run: |
          url=$(gcloud run services describe omicron-console-dev --format 'value(status.url)' --platform=managed --region=us-central1 | sed 's|https://|https://main---|g')
          echo "::set-output name=url::$url"
