name: Recreate figma-tokens branch

on:
  delete:
    branch: figma-tokens

jobs:
  recreate-figma-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'figma-tokens'
