name: license-check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fix License Header
      uses: apache/skywalking-eyes/header@5dfa68f93380a5e57259faaf95088b7f133b5778
      with:
        mode: fix
    - name: Apply Changes
      uses: EndBug/add-and-commit@v9
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        author_name: License Bot
        author_email: license_bot@github.com
        message: 'Automatic application of license header'