name: Reformat

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Format
        run: yarn fmt

      - uses: EndBug/add-and-commit@v7
        with:
          add: .
          message: 'Bot commit: format with prettier'
          default_author: github_actions
