name: Reformat

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Format
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn fmt .

      - uses: EndBug/add-and-commit@v7
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          add: .
          message: 'LOOK ON MY REFORMAT, YE MIGHTY, AND DESPAIR!' # At this point it's almost traditional
          default_author: github_actions
