name: Sync Config

on:
  push:
    branches-ignore:
      - main
    paths:
      - '.github/workflows/sync-config.yml'
      - '.github/workflows/deploy-vm.yml'

jobs:
  update-packer:
    runs-on: ubuntu-latest
    name: Update deploy-vm sha in packer.yaml
    outputs:
      deploy-vm-sha: ${{ steps.update-packer.outputs.deploy-vm-sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Replace sha
        run: |
          PKR_PATH=./.github/workflows/packer.yaml
          PACKER_YML="$(cat $PKR_PATH)"
          OLD_SHA="$(echo $PACKER_YML | grep -oP 'deploy-vm.yml@(\w+)' | cut -d @ -f2)"
          NEW_SHA="$(git ls-files -s ./.github/workflows/deploy-vm.yml | cut -d ' ' -f2)"
          echo "${PACKER_YML/$OLD_SHA/$NEW_SHA}" > $PKR_PATH
          cat $PKR_PATH
      - uses: EndBug/add-and-commit@v7
        with:
          add: .github/workflows/packer.yaml
          message: 'Update deploy-vm.yml sha in packer.yaml'
          default_author: github_actions
