name: 'Visual Regression Testing'

# Event for the workflow
on:
  push:
    paths:
      - 'libs/ui/**'
      - 'libs/table/**'
      - 'libs/pagination/**'
      - 'libs/util/**'
      - 'tailwind.config.js'
      - 'postcss.config.js'
      - '.github/workflows/visual-test.yaml'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
